<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(AvsCurrentTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Avalonia.Base\Avalonia.Base.csproj" />
    <ProjectReference Include="..\Avalonia.Rust.Interop\Avalonia.Rust.Interop.csproj" />
  </ItemGroup>
  <Import Project="..\..\build\NullableEnable.props" />
  <Import Project="..\..\build\TrimmingEnable.props" />
</Project>
