@clr-namespace Avalonia.Host.Ownership.MicroCom
@clr-access internal
@clr-map bool int
@cpp-preamble @@
#pragma once
#include "stdint.h"
@@

[uuid(587641ae-e4be-49bb-86a6-16c826a60f73)]
interface IAvnMicroComOwnershipProbe : IUnknown
{
    HRESULT GetValue(int* value);
}
