//! Generated by avalonia-bindgen. Do not edit.
#![allow(dead_code)]

use avalonia_sys as sys;
use crate::{runtime::{with_factory, AsControl}, Result};

#[repr(i32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Orientation {
    Horizontal = 0,
    Vertical = 1,
}

impl TryFrom<i32> for Orientation {
    type Error = crate::Error;
    fn try_from(value: i32) -> Result<Self> {
        match value {
            0 => Ok(Self::Horizontal),
            1 => Ok(Self::Vertical),
            _ => Err(crate::Error::InvalidEnumValue(value)),
        }
    }
}

#[derive(Debug)]
pub struct ControlList {
    pub(crate) raw: sys::ComPtr<sys::IAvnControlList>,
}

impl ControlList {
    pub fn len(&self) -> Result<usize> { Ok(self.raw.len()?) }
    pub fn is_empty(&self) -> Result<bool> { Ok(self.len()? == 0) }
    pub fn add(&self, value: impl AsControl) -> Result<()> {
        let value = value.as_control()?;
        Ok(self.raw.add(&value)?)
    }
    pub fn remove(&self, index: usize) -> Result<()> { Ok(self.raw.remove(index)?) }
    pub fn clear(&self) -> Result<()> { Ok(self.raw.clear()?) }
}

#[derive(Debug)]
pub struct AvaloniaObject {
    pub(crate) raw: sys::ComPtr<sys::IAvnAvaloniaObject>,
}

impl AvaloniaObject {
    pub fn new() -> Result<Self> {
        with_factory(|factory| factory.create_avalonia_object())
            .map(|raw| Self { raw })
    }
}


#[derive(Debug)]
pub struct Button {
    pub(crate) raw: sys::ComPtr<sys::IAvnButton>,
}

impl Button {
    pub fn new() -> Result<Self> {
        with_factory(|factory| factory.create_button())
            .map(|raw| Self { raw })
    }
    pub fn is_enabled(&self) -> Result<bool> { Ok(self.raw.get_is_enabled()?) }
    pub fn set_enabled(&self, value: bool) -> Result<()> {
        Ok(self.raw.set_is_enabled(value)?)
    }
    pub fn enabled(self, value: bool) -> Result<Self> {
        self.set_enabled(value)?;
        Ok(self)
    }
    pub fn get_content(&self) -> Result<Option<Control>> {
        Ok(self.raw.get_content()?.map(|raw| Control { raw }))
    }
    pub fn set_content(&self, value: impl AsControl) -> Result<()> {
        let value = value.as_control()?;
        Ok(self.raw.set_content(Some(&value))?)
    }
    pub fn content(self, value: impl AsControl) -> Result<Self> {
        self.set_content(value)?;
        Ok(self)
    }
}

impl AsControl for Button {
    fn as_control(&self) -> Result<sys::ComPtr<sys::IAvnControl>> {
        Ok(self.raw.query_interface()?)
    }
}

#[derive(Debug)]
pub struct ContentControl {
    pub(crate) raw: sys::ComPtr<sys::IAvnContentControl>,
}

impl ContentControl {
    pub fn new() -> Result<Self> {
        with_factory(|factory| factory.create_content_control())
            .map(|raw| Self { raw })
    }
    pub fn is_enabled(&self) -> Result<bool> { Ok(self.raw.get_is_enabled()?) }
    pub fn set_enabled(&self, value: bool) -> Result<()> {
        Ok(self.raw.set_is_enabled(value)?)
    }
    pub fn enabled(self, value: bool) -> Result<Self> {
        self.set_enabled(value)?;
        Ok(self)
    }
    pub fn get_content(&self) -> Result<Option<Control>> {
        Ok(self.raw.get_content()?.map(|raw| Control { raw }))
    }
    pub fn set_content(&self, value: impl AsControl) -> Result<()> {
        let value = value.as_control()?;
        Ok(self.raw.set_content(Some(&value))?)
    }
    pub fn content(self, value: impl AsControl) -> Result<Self> {
        self.set_content(value)?;
        Ok(self)
    }
}

impl AsControl for ContentControl {
    fn as_control(&self) -> Result<sys::ComPtr<sys::IAvnControl>> {
        Ok(self.raw.query_interface()?)
    }
}

#[derive(Debug)]
pub struct Control {
    pub(crate) raw: sys::ComPtr<sys::IAvnControl>,
}

impl Control {
    pub fn new() -> Result<Self> {
        with_factory(|factory| factory.create_control())
            .map(|raw| Self { raw })
    }
    pub fn is_enabled(&self) -> Result<bool> { Ok(self.raw.get_is_enabled()?) }
    pub fn set_enabled(&self, value: bool) -> Result<()> {
        Ok(self.raw.set_is_enabled(value)?)
    }
    pub fn enabled(self, value: bool) -> Result<Self> {
        self.set_enabled(value)?;
        Ok(self)
    }
}

impl AsControl for Control {
    fn as_control(&self) -> Result<sys::ComPtr<sys::IAvnControl>> {
        Ok(self.raw.query_interface()?)
    }
}

#[derive(Debug)]
pub struct Panel {
    pub(crate) raw: sys::ComPtr<sys::IAvnPanel>,
}

impl Panel {
    pub fn new() -> Result<Self> {
        with_factory(|factory| factory.create_panel())
            .map(|raw| Self { raw })
    }
    pub fn is_enabled(&self) -> Result<bool> { Ok(self.raw.get_is_enabled()?) }
    pub fn set_enabled(&self, value: bool) -> Result<()> {
        Ok(self.raw.set_is_enabled(value)?)
    }
    pub fn enabled(self, value: bool) -> Result<Self> {
        self.set_enabled(value)?;
        Ok(self)
    }
    pub fn children(&self) -> Result<ControlList> {
        Ok(ControlList { raw: self.raw.get_children()? })
    }
    pub fn child(self, value: impl AsControl) -> Result<Self> {
        self.children()?.add(value)?;
        Ok(self)
    }
}

impl AsControl for Panel {
    fn as_control(&self) -> Result<sys::ComPtr<sys::IAvnControl>> {
        Ok(self.raw.query_interface()?)
    }
}

#[derive(Debug)]
pub struct StackPanel {
    pub(crate) raw: sys::ComPtr<sys::IAvnStackPanel>,
}

impl StackPanel {
    pub fn new() -> Result<Self> {
        with_factory(|factory| factory.create_stack_panel())
            .map(|raw| Self { raw })
    }
    pub fn is_enabled(&self) -> Result<bool> { Ok(self.raw.get_is_enabled()?) }
    pub fn set_enabled(&self, value: bool) -> Result<()> {
        Ok(self.raw.set_is_enabled(value)?)
    }
    pub fn enabled(self, value: bool) -> Result<Self> {
        self.set_enabled(value)?;
        Ok(self)
    }
    pub fn children(&self) -> Result<ControlList> {
        Ok(ControlList { raw: self.raw.get_children()? })
    }
    pub fn child(self, value: impl AsControl) -> Result<Self> {
        self.children()?.add(value)?;
        Ok(self)
    }
    pub fn get_spacing(&self) -> Result<f64> { Ok(self.raw.get_spacing()?) }
    pub fn set_spacing(&self, value: f64) -> Result<()> {
        Ok(self.raw.set_spacing(value)?)
    }
    pub fn spacing(self, value: f64) -> Result<Self> {
        self.set_spacing(value)?;
        Ok(self)
    }
    pub fn get_orientation(&self) -> Result<Orientation> {
        let value = self.raw.get_orientation()?;
        Orientation::try_from(value)
    }
    pub fn set_orientation(&self, value: Orientation) -> Result<()> {
        Ok(self.raw.set_orientation(value as i32)?)
    }
    pub fn orientation(self, value: Orientation) -> Result<Self> {
        self.set_orientation(value)?;
        Ok(self)
    }
}

impl AsControl for StackPanel {
    fn as_control(&self) -> Result<sys::ComPtr<sys::IAvnControl>> {
        Ok(self.raw.query_interface()?)
    }
}

#[derive(Debug)]
pub struct TextBlock {
    pub(crate) raw: sys::ComPtr<sys::IAvnTextBlock>,
}

impl TextBlock {
    pub fn new() -> Result<Self> {
        with_factory(|factory| factory.create_text_block())
            .map(|raw| Self { raw })
    }
    pub fn is_enabled(&self) -> Result<bool> { Ok(self.raw.get_is_enabled()?) }
    pub fn set_enabled(&self, value: bool) -> Result<()> {
        Ok(self.raw.set_is_enabled(value)?)
    }
    pub fn enabled(self, value: bool) -> Result<Self> {
        self.set_enabled(value)?;
        Ok(self)
    }
    pub fn set_text(&self, value: impl AsRef<str>) -> Result<()> {
        let value: Vec<u16> = value.as_ref().encode_utf16().chain(Some(0)).collect();
        Ok(self.raw.set_text(Some(&value))?)
    }
    pub fn text(self, value: impl AsRef<str>) -> Result<Self> {
        self.set_text(value)?;
        Ok(self)
    }
}

impl AsControl for TextBlock {
    fn as_control(&self) -> Result<sys::ComPtr<sys::IAvnControl>> {
        Ok(self.raw.query_interface()?)
    }
}

#[derive(Debug)]
pub struct Window {
    pub(crate) raw: sys::ComPtr<sys::IAvnWindow>,
}

impl Window {
    pub fn new() -> Result<Self> {
        with_factory(|factory| factory.create_window())
            .map(|raw| Self { raw })
    }
    pub fn is_enabled(&self) -> Result<bool> { Ok(self.raw.get_is_enabled()?) }
    pub fn set_enabled(&self, value: bool) -> Result<()> {
        Ok(self.raw.set_is_enabled(value)?)
    }
    pub fn enabled(self, value: bool) -> Result<Self> {
        self.set_enabled(value)?;
        Ok(self)
    }
    pub fn get_content(&self) -> Result<Option<Control>> {
        Ok(self.raw.get_content()?.map(|raw| Control { raw }))
    }
    pub fn set_content(&self, value: impl AsControl) -> Result<()> {
        let value = value.as_control()?;
        Ok(self.raw.set_content(Some(&value))?)
    }
    pub fn content(self, value: impl AsControl) -> Result<Self> {
        self.set_content(value)?;
        Ok(self)
    }
    pub fn set_title(&self, value: impl AsRef<str>) -> Result<()> {
        let value: Vec<u16> = value.as_ref().encode_utf16().chain(Some(0)).collect();
        Ok(self.raw.set_title(Some(&value))?)
    }
    pub fn title(self, value: impl AsRef<str>) -> Result<Self> {
        self.set_title(value)?;
        Ok(self)
    }
    pub fn close(&self) -> Result<()> { Ok(self.raw.close()?) }
    pub fn show(&self) -> Result<()> { Ok(self.raw.show()?) }
    pub fn show_with_window(&self, owner: &Window) -> Result<()> { Ok(self.raw.show_with_window(&owner.raw)?) }
}

impl AsControl for Window {
    fn as_control(&self) -> Result<sys::ComPtr<sys::IAvnControl>> {
        Ok(self.raw.query_interface()?)
    }
}

