using Avalonia.Projection.Ir;

namespace Avalonia.Projection.Generator;

public static class ComSourceEmitter
{
    public static IReadOnlyDictionary<string, string> Emit(ProjectionIr ir)
    {
        var files = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var type in ir.Types.Where(t => t.Kind == ProjectedTypeKind.Interface))
            files[type.Name + ".g.cs"] = EmitInterface(type);
        return files;
    }

    public static string EmitInterface(ProjectedType type)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Runtime.InteropServices.Marshalling;");
        sb.AppendLine();
        var ns = NamespaceOf(type.FullName);
        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine("[GeneratedComInterface(StringMarshalling = StringMarshalling.Utf16)]");
        if (!string.IsNullOrEmpty(type.Iid))
            sb.AppendLine($"[Guid(\"{type.Iid}\")]");

        var bases = type.BaseFullName is { } b ? $" : {SimpleName(b)}" : "";
        sb.AppendLine($"public partial interface {type.Name}{bases}");
        sb.AppendLine("{");

        foreach (var method in type.Methods)
        {
            if (method.PreserveSig)
                sb.AppendLine("    [PreserveSig]");
            sb.Append("    ");
            sb.Append(CSharpType(method.ReturnKind, null, false));
            sb.Append(' ');
            sb.Append(method.Name);
            sb.Append('(');
            sb.Append(string.Join(", ", method.Parameters.Select(FormatParameter)));
            sb.AppendLine(");");
            sb.AppendLine();
        }

        foreach (var prop in type.Properties)
        {
            sb.Append("    ");
            sb.Append(CSharpType(prop.Kind, prop.InterfaceName, false));
            sb.Append(' ');
            sb.Append(prop.Name);
            sb.Append(" { ");
            if (prop.CanRead)
                sb.Append("get; ");
            if (prop.CanWrite)
                sb.Append("set; ");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string FormatParameter(ProjectedParameter p)
    {
        var prefix = p.Direction switch
        {
            ParameterDirection.Out => "out ",
            ParameterDirection.InOut => "ref ",
            _ => "",
        };
        var ty = CSharpType(p.Kind, p.InterfaceName, p.IsNullable && p.Direction != ParameterDirection.Out);
        if (p.IsNullable && p.Direction == ParameterDirection.Out && p.Kind is MarshallingKind.StringUtf16 or MarshallingKind.ComInterface)
            ty += "?";
        return $"{prefix}{ty} {p.Name}";
    }

    private static string CSharpType(MarshallingKind kind, string? interfaceName, bool nullable) =>
        kind switch
        {
            MarshallingKind.Void => "void",
            MarshallingKind.I32 => "int",
            MarshallingKind.I64 => "long",
            MarshallingKind.F32 => "float",
            MarshallingKind.F64 => "double",
            MarshallingKind.Bool => "bool",
            MarshallingKind.StringUtf16 => nullable ? "string?" : "string",
            MarshallingKind.ComInterface => (interfaceName is null ? "object" : SimpleName(interfaceName)) + (nullable ? "?" : ""),
            _ => throw new InvalidOperationException($"Cannot emit C# for {kind}"),
        };

    private static string? NamespaceOf(string fullName)
    {
        var i = fullName.LastIndexOf('.');
        return i < 0 ? null : fullName[..i];
    }

    private static string SimpleName(string fullName)
    {
        var i = fullName.LastIndexOf('.');
        return i < 0 ? fullName : fullName[(i + 1)..];
    }
}
