using System.Text;
using System.Text.Json;
using Avalonia.Projection.Ir;

namespace Avalonia.Projection.Generator;

public static class ViewModelSourceEmitter
{
    public static IReadOnlyDictionary<string, string> EmitCSharp(ViewModelIr ir)
    {
        ir.Validate();
        var files = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var model in ir.Models)
            files[$"{model.Name}Adapter.g.cs"] = EmitCSharpAdapter(model);
        files["RustViewRegistry.g.cs"] = EmitRegistry(ir);
        return files;
    }

    public static string EmitRust(ViewModelIr ir)
    {
        ir.Validate();
        var sb = new StringBuilder(
            "//! Generated from view-model.ir.json. Do not edit.\n\n");
        foreach (var model in ir.Models)
            EmitRustModel(sb, model, ir.Views.Where(view => view.Model == model.Name));
        return sb.ToString().TrimEnd() + "\n";
    }

    public static string EmitContract(ViewModelIr ir)
    {
        ir.Validate();
        var sb = new StringBuilder();
        sb.AppendLine("# Generated Rust view-model contract");
        sb.AppendLine();
        sb.AppendLine($"Schema version: `{ir.Version}`");
        foreach (var model in ir.Models)
        {
            sb.AppendLine();
            sb.AppendLine($"## Model `{model.Name}` (`{model.Id}`)");
            sb.AppendLine();
            sb.AppendLine("| Kind | ID | Name | Type | Direction |");
            sb.AppendLine("| --- | ---: | --- | --- | --- |");
            foreach (var property in model.Properties)
                sb.AppendLine($"| Property | {property.Id} | `{property.Name}` | `{property.Kind}` | {(property.Writable ? "Rust and managed" : "Rust to managed")} |");
            foreach (var collection in model.Collections)
                sb.AppendLine($"| Collection | {collection.Id} | `{collection.Name}` | `{collection.ElementKind}` | Rust to managed |");
            foreach (var command in model.Commands)
            {
                var parameter = command.ParameterProperty is null
                    ? "None"
                    : $"`{command.ParameterProperty}`";
                sb.AppendLine($"| {(command.IsAsync ? "Async command" : "Command")} | {command.Id} | `{command.Name}` | {parameter} | Managed to Rust |");
            }
        }
        if (ir.Views.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("## Views");
            sb.AppendLine();
            sb.AppendLine("| ID | Name | Model | Managed type |");
            sb.AppendLine("| ---: | --- | --- | --- |");
            foreach (var view in ir.Views)
                sb.AppendLine($"| {view.Id} | `{view.Name}` | `{view.Model}` | `{view.ManagedTypeName}` |");
        }
        return sb.ToString();
    }

    private static string EmitCSharpAdapter(ViewModelDefinition model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.ObjectModel;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Runtime.InteropServices.Marshalling;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Windows.Input;");
        sb.AppendLine("using Avalonia.Rust.Interop;");
        sb.AppendLine("using Avalonia.Threading;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.ManagedNamespace};");
        sb.AppendLine();
        sb.AppendLine("[GeneratedComClass]");
        sb.AppendLine($"public sealed partial class {model.Name}Adapter : IAvnRustVmSink, INotifyPropertyChanged, IDisposable");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IAvnRustViewModel _model;");
        sb.AppendLine("    private int _disposed;");
        foreach (var property in model.Properties)
            sb.AppendLine($"    private {CSharpType(property.Kind)} _{Lower(property.Name)} = {CSharpInitial(property)};");
        sb.AppendLine();
        sb.AppendLine($"    public {model.Name}Adapter(IAvnRustViewModel model)");
        sb.AppendLine("    {");
        sb.AppendLine("        _model = model;");
        foreach (var command in model.Commands)
        {
            var invocation = command.IsAsync ? "BeginAsync" : "Execute";
            var parameter = command.ParameterProperty is null
                ? "null"
                : command.ParameterProperty;
            sb.AppendLine($"        {command.Name}Command = new DelegateCommand(() => Check(_model.{invocation}({command.Id}, {parameter})));");
        }
        sb.AppendLine("        Check(_model.Attach(this));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public event PropertyChangedEventHandler? PropertyChanged;");
        sb.AppendLine();
        foreach (var property in model.Properties)
        {
            sb.AppendLine($"    public {CSharpType(property.Kind)} {property.Name}");
            sb.AppendLine("    {");
            sb.AppendLine($"        get => _{Lower(property.Name)};");
            if (property.Writable)
            {
                sb.AppendLine("        set");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (Equals(_{Lower(property.Name)}, value))");
                sb.AppendLine("                return;");
                sb.AppendLine($"            Check(_model.Set{TransportSuffix(property.Kind)}({property.Id}, {CSharpToTransport(property.Kind, "value")}));");
                sb.AppendLine("        }");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        foreach (var collection in model.Collections)
            sb.AppendLine($"    public ObservableCollection<{CSharpType(collection.ElementKind)}> {collection.Name} {{ get; }} = [];");
        if (model.Collections.Count > 0)
            sb.AppendLine();
        foreach (var command in model.Commands)
            sb.AppendLine($"    public ICommand {command.Name}Command {{ get; }}");
        sb.AppendLine();
        EmitCSharpSinkMethods(sb, model);
        sb.AppendLine("    public void Dispose()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (Interlocked.Exchange(ref _disposed, 1) == 0)");
        sb.AppendLine("            Check(_model.Detach());");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private int Apply(Action action)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (Volatile.Read(ref _disposed) != 0) return 0;");
        sb.AppendLine("        void ApplyIfAlive()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (Volatile.Read(ref _disposed) == 0) action();");
        sb.AppendLine("        }");
        sb.AppendLine("        if (Dispatcher.UIThread.CheckAccess()) ApplyIfAlive();");
        sb.AppendLine("        else Dispatcher.UIThread.Post(ApplyIfAlive);");
        sb.AppendLine("        return 0;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void Check(int hresult)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (hresult < 0) Marshal.ThrowExceptionForHR(hresult);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private void SetField<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (Equals(field, value)) return;");
        sb.AppendLine("        field = value;");
        sb.AppendLine("        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private sealed class DelegateCommand(Action execute) : ICommand");
        sb.AppendLine("    {");
        sb.AppendLine("        public event EventHandler? CanExecuteChanged { add { } remove { } }");
        sb.AppendLine("        public bool CanExecute(object? parameter) => true;");
        sb.AppendLine("        public void Execute(object? parameter) => execute();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitCSharpSinkMethods(StringBuilder sb, ViewModelDefinition model)
    {
        foreach (var kind in Enum.GetValues<ViewModelValueKind>())
        {
            var properties = model.Properties.Where(property => property.Kind == kind).ToArray();
            sb.AppendLine($"    public int Set{TransportSuffix(kind)}(int propertyId, {CSharpTransportType(kind)} value) => propertyId switch");
            sb.AppendLine("    {");
            foreach (var property in properties)
                sb.AppendLine($"        {property.Id} => Apply(() => SetField(ref _{Lower(property.Name)}, {CSharpFromTransport(kind, "value")}, nameof({property.Name}))),");
            sb.AppendLine("        _ => unchecked((int)0x80070057),");
            sb.AppendLine("    };");
            sb.AppendLine();
        }
        sb.AppendLine("    public int AddString(int collectionId, string? value) => collectionId switch");
        sb.AppendLine("    {");
        foreach (var collection in model.Collections.Where(collection => collection.ElementKind == ViewModelValueKind.String))
            sb.AppendLine($"        {collection.Id} => Apply(() => {collection.Name}.Add(value ?? \"\")),");
        sb.AppendLine("        _ => unchecked((int)0x80070057),");
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static string EmitRegistry(ViewModelIr ir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Avalonia.Controls;");
        sb.AppendLine("using Avalonia.Rust.Interop;");
        sb.AppendLine();
        sb.AppendLine("namespace Avalonia.Host.Generated.ViewModels;");
        sb.AppendLine();
        sb.AppendLine("internal static class RustViewRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    internal static Window Create(int viewId, IAvnRustViewModel model) => viewId switch");
        sb.AppendLine("    {");
        foreach (var view in ir.Views)
            sb.AppendLine($"        {view.Id} => new global::{view.ManagedTypeName}(model),");
        sb.AppendLine("        _ => throw new global::System.ArgumentOutOfRangeException(nameof(viewId)),");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitRustModel(
        StringBuilder sb,
        ViewModelDefinition model,
        IEnumerable<ViewDefinition> views)
    {
        var traitName = model.Name;
        var sinkName = $"{model.Name}Sink";
        sb.AppendLine("#[derive(Clone, Debug)]");
        sb.AppendLine($"pub struct {sinkName}(crate::view_model::ViewModelSink);");
        sb.AppendLine();
        sb.AppendLine($"impl {sinkName} {{");
        foreach (var property in model.Properties)
            sb.AppendLine($"    pub fn set_{Snake(property.Name)}(&self, value: {RustInputType(property.Kind)}) -> crate::Result<()> {{ self.0.set_{Snake(TransportSuffix(property.Kind))}({property.Id}, value) }}");
        foreach (var collection in model.Collections)
            sb.AppendLine($"    pub fn add_{Snake(collection.Name)}(&self, value: {RustInputType(collection.ElementKind)}) -> crate::Result<()> {{ self.0.add_string({collection.Id}, value) }}");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"pub trait {traitName}: Send + 'static {{");
        sb.AppendLine($"    fn attach(&mut self, sink: {sinkName}) -> crate::Result<()>;");
        sb.AppendLine("    fn detach(&mut self) -> crate::Result<()>;");
        foreach (var property in model.Properties.Where(property => property.Writable))
            sb.AppendLine($"    fn set_{Snake(property.Name)}(&mut self, value: {RustOwnedType(property.Kind)}) -> crate::Result<()>;");
        foreach (var command in model.Commands)
        {
            var parameter = command.ParameterProperty is null
                ? ""
                : $", value: {RustOwnedType(model.Properties.Single(property => property.Name == command.ParameterProperty).Kind)}";
            sb.AppendLine($"    fn {Snake(command.Name)}(&mut self{parameter}) -> crate::Result<()>;");
        }
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"struct {traitName}Dispatch<T: {traitName}> {{ model: T }}");
        sb.AppendLine();
        sb.AppendLine($"impl<T: {traitName}> crate::view_model::DynamicViewModel for {traitName}Dispatch<T> {{");
        sb.AppendLine($"    fn attach(&mut self, sink: crate::view_model::ViewModelSink) -> crate::Result<()> {{ self.model.attach({sinkName}(sink)) }}");
        sb.AppendLine("    fn detach(&mut self) -> crate::Result<()> { self.model.detach() }");
        EmitRustPropertyDispatch(sb, model, ViewModelValueKind.String);
        EmitRustPropertyDispatch(sb, model, ViewModelValueKind.Integer);
        EmitRustPropertyDispatch(sb, model, ViewModelValueKind.Boolean);
        EmitRustPropertyDispatch(sb, model, ViewModelValueKind.Double);
        EmitRustCommandDispatch(sb, model, asyncCommands: false);
        EmitRustCommandDispatch(sb, model, asyncCommands: true);
        sb.AppendLine("}");
        sb.AppendLine();
        foreach (var view in views)
            sb.AppendLine($"impl crate::AppScope {{ pub fn mount_{Snake(view.Name)}(&self, model: impl {traitName}) -> crate::Result<()> {{ self.mount_dynamic_view_model({view.Id}, {traitName}Dispatch {{ model }}) }} }}");
        sb.AppendLine();
    }

    private static void EmitRustPropertyDispatch(
        StringBuilder sb,
        ViewModelDefinition model,
        ViewModelValueKind kind)
    {
        var transport = Snake(TransportSuffix(kind));
        var properties = model.Properties
            .Where(property => property.Writable && property.Kind == kind)
            .ToArray();
        var valueName = properties.Length == 0 ? "_value" : "value";
        sb.AppendLine($"    fn set_{transport}(&mut self, property_id: i32, {valueName}: {RustOwnedType(kind)}) -> crate::Result<()> {{");
        if (properties.Length == 0)
        {
            sb.AppendLine("        Err(crate::Error::InvalidViewModelMember { kind: \"property\", id: property_id })");
            sb.AppendLine("    }");
            return;
        }
        sb.AppendLine("        match property_id {");
        foreach (var property in properties)
            sb.AppendLine($"            {property.Id} => self.model.set_{Snake(property.Name)}(value),");
        sb.AppendLine($"            _ => Err(crate::Error::InvalidViewModelMember {{ kind: \"property\", id: property_id }}),");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void EmitRustCommandDispatch(
        StringBuilder sb,
        ViewModelDefinition model,
        bool asyncCommands)
    {
        var method = asyncCommands ? "begin_async" : "execute";
        var commands = model.Commands.Where(command => command.IsAsync == asyncCommands).ToArray();
        var parameterName = commands.Any(command => command.ParameterProperty is not null)
            ? "parameter"
            : "_parameter";
        sb.AppendLine($"    fn {method}(&mut self, command_id: i32, {parameterName}: Option<String>) -> crate::Result<()> {{");
        sb.AppendLine("        match command_id {");
        foreach (var command in commands)
        {
            var argument = command.ParameterProperty is null
                ? ""
                : "parameter.unwrap_or_default()";
            sb.AppendLine($"            {command.Id} => self.model.{Snake(command.Name)}({argument}),");
        }
        sb.AppendLine($"            _ => Err(crate::Error::InvalidViewModelMember {{ kind: \"command\", id: command_id }}),");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static string CSharpType(ViewModelValueKind kind) => kind switch
    {
        ViewModelValueKind.String => "string",
        ViewModelValueKind.Integer => "long",
        ViewModelValueKind.Boolean => "bool",
        ViewModelValueKind.Double => "double",
        _ => throw new ArgumentOutOfRangeException(nameof(kind)),
    };

    private static string CSharpTransportType(ViewModelValueKind kind) =>
        kind == ViewModelValueKind.Boolean ? "int" : CSharpType(kind) + (kind == ViewModelValueKind.String ? "?" : "");

    private static string CSharpInitial(ViewModelProperty property) => property.Kind switch
    {
        ViewModelValueKind.String => JsonSerializer.Serialize(property.InitialString ?? ""),
        ViewModelValueKind.Integer => (property.InitialInteger ?? 0).ToString(
            global::System.Globalization.CultureInfo.InvariantCulture),
        ViewModelValueKind.Boolean => (property.InitialBoolean ?? false) ? "true" : "false",
        ViewModelValueKind.Double => (property.InitialDouble ?? 0).ToString(
            "R",
            global::System.Globalization.CultureInfo.InvariantCulture),
        _ => throw new ArgumentOutOfRangeException(),
    };

    private static string CSharpToTransport(ViewModelValueKind kind, string value) =>
        kind == ViewModelValueKind.Boolean ? $"({value} ? 1 : 0)" : value;

    private static string CSharpFromTransport(ViewModelValueKind kind, string value) => kind switch
    {
        ViewModelValueKind.String => $"{value} ?? \"\"",
        ViewModelValueKind.Boolean => $"{value} != 0",
        _ => value,
    };

    private static string TransportSuffix(ViewModelValueKind kind) => kind switch
    {
        ViewModelValueKind.String => "String",
        ViewModelValueKind.Integer => "Integer",
        ViewModelValueKind.Boolean => "Boolean",
        ViewModelValueKind.Double => "Double",
        _ => throw new ArgumentOutOfRangeException(nameof(kind)),
    };

    private static string RustInputType(ViewModelValueKind kind) =>
        kind == ViewModelValueKind.String ? "impl AsRef<str>" : RustOwnedType(kind);

    private static string RustOwnedType(ViewModelValueKind kind) => kind switch
    {
        ViewModelValueKind.String => "String",
        ViewModelValueKind.Integer => "i64",
        ViewModelValueKind.Boolean => "bool",
        ViewModelValueKind.Double => "f64",
        _ => throw new ArgumentOutOfRangeException(nameof(kind)),
    };

    private static string Lower(string value) =>
        char.ToLowerInvariant(value[0]) + value[1..];

    private static string Snake(string value)
    {
        var sb = new StringBuilder();
        for (var index = 0; index < value.Length; index++)
        {
            var character = value[index];
            if (char.IsUpper(character) && index > 0)
                sb.Append('_');
            sb.Append(char.ToLowerInvariant(character));
        }
        return sb.ToString();
    }
}
