//! Generated by avalonia-bindgen. Do not edit.
#![allow(dead_code, non_snake_case)]

use crate::com::{ComInterface, ComPtr, IUnknown};
use crate::guid::Guid;
use crate::hresult::{self, Error, Result};
use std::ffi::c_void;
use std::ptr;

pub const I_AVN_BUTTON_CLICK_HANDLER_IID: Guid = Guid { data1: 0x05D26ED4, data2: 0xDA87, data3: 0x5CBB, data4: [0xA0, 0x47, 0x81, 0x77, 0x23, 0x91, 0x17, 0x96] };

#[repr(C)]
struct IAvnButtonClickHandlerVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    invoke: unsafe extern "system" fn(*mut IAvnButtonClickHandler) -> i32,
}

#[repr(C)]
pub struct IAvnButtonClickHandler {
    vtbl: *const IAvnButtonClickHandlerVtbl,
}

unsafe impl ComInterface for IAvnButtonClickHandler {
    const IID: Guid = I_AVN_BUTTON_CLICK_HANDLER_IID;
}

impl ComPtr<IAvnButtonClickHandler> {
    pub fn invoke(&self) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().invoke)(self.as_raw());
            hresult::check(hr)
        }
    }
}

static I_AVN_BUTTON_CLICK_HANDLER_VTBL: IAvnButtonClickHandlerVtbl = IAvnButtonClickHandlerVtbl {
    query_interface: i_avn_button_click_handler_query_interface,
    add_ref: i_avn_button_click_handler_add_ref,
    release: i_avn_button_click_handler_release,
    invoke: i_avn_button_click_handler_invoke,
};

pub fn button_click_handler(callback: impl FnMut() -> Result<()> + Send + 'static) -> ComPtr<IAvnButtonClickHandler> {
    crate::event_callback::create(IAvnButtonClickHandler { vtbl: &I_AVN_BUTTON_CLICK_HANDLER_VTBL }, callback)
}

unsafe extern "system" fn i_avn_button_click_handler_query_interface(this: *mut IUnknown, iid: *const Guid, result: *mut *mut c_void) -> i32 {
    crate::event_callback::query_interface::<IAvnButtonClickHandler>(this, iid, result)
}

unsafe extern "system" fn i_avn_button_click_handler_add_ref(this: *mut IUnknown) -> u32 {
    crate::event_callback::add_ref::<IAvnButtonClickHandler>(this)
}

unsafe extern "system" fn i_avn_button_click_handler_release(this: *mut IUnknown) -> u32 {
    crate::event_callback::release::<IAvnButtonClickHandler>(this)
}

unsafe extern "system" fn i_avn_button_click_handler_invoke(this: *mut IAvnButtonClickHandler) -> i32 {
    crate::event_callback::invoke::<IAvnButtonClickHandler>(this)
}

pub const I_AVN_CONTROL_LIST_IID: Guid = Guid { data1: 0x2FDCB505, data2: 0x4C03, data3: 0x5F63, data4: [0x8E, 0x3D, 0xC4, 0xB1, 0x86, 0xA8, 0xAF, 0xE1] };

#[repr(C)]
struct IAvnControlListVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_count: unsafe extern "system" fn(*mut IAvnControlList, *mut i32) -> i32,
    get_at: unsafe extern "system" fn(*mut IAvnControlList, i32, *mut *mut IAvnControl) -> i32,
    add: unsafe extern "system" fn(*mut IAvnControlList, *mut IAvnControl) -> i32,
    remove_at: unsafe extern "system" fn(*mut IAvnControlList, i32) -> i32,
    clear: unsafe extern "system" fn(*mut IAvnControlList) -> i32,
}

#[repr(C)]
pub struct IAvnControlList {
    vtbl: *const IAvnControlListVtbl,
}

unsafe impl ComInterface for IAvnControlList {
    const IID: Guid = I_AVN_CONTROL_LIST_IID;
}

impl ComPtr<IAvnControlList> {
    pub fn len(&self) -> Result<usize> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_count)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value as usize)
        }
    }
    pub fn get(&self, index: usize) -> Result<ComPtr<IAvnControl>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_at)(self.as_raw(), index as i32, &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn add(&self, value: &ComPtr<IAvnControl>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().add)(self.as_raw(), value.as_raw());
            hresult::check(hr)
        }
    }
    pub fn remove(&self, index: usize) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().remove_at)(self.as_raw(), index as i32);
            hresult::check(hr)
        }
    }
    pub fn clear(&self) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().clear)(self.as_raw());
            hresult::check(hr)
        }
    }
}

pub const I_AVN_AVALONIA_OBJECT_IID: Guid = Guid { data1: 0xC6AC58CF, data2: 0x45CF, data3: 0x54BF, data4: [0xAB, 0x0B, 0x55, 0x55, 0x6F, 0x03, 0xE3, 0x9A] };

#[repr(C)]
struct IAvnAvaloniaObjectVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnAvaloniaObject, *mut i64) -> i32,
}

#[repr(C)]
pub struct IAvnAvaloniaObject {
    vtbl: *const IAvnAvaloniaObjectVtbl,
}

unsafe impl ComInterface for IAvnAvaloniaObject {
    const IID: Guid = I_AVN_AVALONIA_OBJECT_IID;
}

impl ComPtr<IAvnAvaloniaObject> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
}

pub const I_AVN_BUTTON_IID: Guid = Guid { data1: 0x514BBD75, data2: 0xB270, data3: 0x51D6, data4: [0xB6, 0xCC, 0x56, 0x85, 0x0A, 0x9D, 0xC4, 0x8A] };

#[repr(C)]
struct IAvnButtonVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnButton, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnButton, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnButton, i32) -> i32,
    get_content: unsafe extern "system" fn(*mut IAvnButton, *mut *mut IAvnControl) -> i32,
    set_content: unsafe extern "system" fn(*mut IAvnButton, *mut IAvnControl) -> i32,
    advise_click: unsafe extern "system" fn(*mut IAvnButton, *mut IAvnButtonClickHandler, *mut i64) -> i32,
    unadvise_click: unsafe extern "system" fn(*mut IAvnButton, i64) -> i32,
}

#[repr(C)]
pub struct IAvnButton {
    vtbl: *const IAvnButtonVtbl,
}

unsafe impl ComInterface for IAvnButton {
    const IID: Guid = I_AVN_BUTTON_IID;
}

impl ComPtr<IAvnButton> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
    pub fn get_content(&self) -> Result<Option<ComPtr<IAvnControl>>> {
        unsafe {
            let mut value: *mut IAvnControl = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_content)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(ComPtr::from_raw(value))
        }
    }
    pub fn set_content(&self, value: Option<&ComPtr<IAvnControl>>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_content)(self.as_raw(), value.map_or(ptr::null_mut(), ComPtr::as_raw));
            hresult::check(hr)
        }
    }
    pub fn advise_click(&self, handler: &ComPtr<IAvnButtonClickHandler>) -> Result<i64> {
        unsafe {
            let mut subscription_id = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().advise_click)(self.as_raw(), handler.as_raw(), &mut subscription_id);
            hresult::check(hr).map(|_| subscription_id)
        }
    }
    pub fn unadvise_click(&self, subscription_id: i64) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().unadvise_click)(self.as_raw(), subscription_id);
            hresult::check(hr)
        }
    }
}

pub const I_AVN_CONTENT_CONTROL_IID: Guid = Guid { data1: 0x885C8CCF, data2: 0xA38F, data3: 0x5B61, data4: [0xAA, 0x71, 0xCA, 0x35, 0xB0, 0xC9, 0xEE, 0x4E] };

#[repr(C)]
struct IAvnContentControlVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnContentControl, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnContentControl, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnContentControl, i32) -> i32,
    get_content: unsafe extern "system" fn(*mut IAvnContentControl, *mut *mut IAvnControl) -> i32,
    set_content: unsafe extern "system" fn(*mut IAvnContentControl, *mut IAvnControl) -> i32,
}

#[repr(C)]
pub struct IAvnContentControl {
    vtbl: *const IAvnContentControlVtbl,
}

unsafe impl ComInterface for IAvnContentControl {
    const IID: Guid = I_AVN_CONTENT_CONTROL_IID;
}

impl ComPtr<IAvnContentControl> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
    pub fn get_content(&self) -> Result<Option<ComPtr<IAvnControl>>> {
        unsafe {
            let mut value: *mut IAvnControl = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_content)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(ComPtr::from_raw(value))
        }
    }
    pub fn set_content(&self, value: Option<&ComPtr<IAvnControl>>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_content)(self.as_raw(), value.map_or(ptr::null_mut(), ComPtr::as_raw));
            hresult::check(hr)
        }
    }
}

pub const I_AVN_CONTROL_IID: Guid = Guid { data1: 0xDC4DEADC, data2: 0x602B, data3: 0x5243, data4: [0x9D, 0x84, 0x3F, 0xB2, 0xC6, 0xB1, 0xD4, 0xA4] };

#[repr(C)]
struct IAvnControlVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnControl, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnControl, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnControl, i32) -> i32,
}

#[repr(C)]
pub struct IAvnControl {
    vtbl: *const IAvnControlVtbl,
}

unsafe impl ComInterface for IAvnControl {
    const IID: Guid = I_AVN_CONTROL_IID;
}

impl ComPtr<IAvnControl> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
}

pub const I_AVN_PANEL_IID: Guid = Guid { data1: 0xE046062C, data2: 0xE709, data3: 0x5BC1, data4: [0x84, 0xAC, 0xB4, 0x63, 0xD5, 0xBE, 0xF5, 0xE8] };

#[repr(C)]
struct IAvnPanelVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnPanel, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnPanel, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnPanel, i32) -> i32,
    get_children: unsafe extern "system" fn(*mut IAvnPanel, *mut *mut IAvnControlList) -> i32,
}

#[repr(C)]
pub struct IAvnPanel {
    vtbl: *const IAvnPanelVtbl,
}

unsafe impl ComInterface for IAvnPanel {
    const IID: Guid = I_AVN_PANEL_IID;
}

impl ComPtr<IAvnPanel> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
    pub fn get_children(&self) -> Result<ComPtr<IAvnControlList>> {
        unsafe {
            let mut value: *mut IAvnControlList = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_children)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
}

pub const I_AVN_STACK_PANEL_IID: Guid = Guid { data1: 0x03AB1A66, data2: 0x3B45, data3: 0x51A5, data4: [0x8E, 0x1D, 0x6E, 0x30, 0x14, 0x1F, 0xDD, 0xC8] };

#[repr(C)]
struct IAvnStackPanelVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnStackPanel, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnStackPanel, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnStackPanel, i32) -> i32,
    get_children: unsafe extern "system" fn(*mut IAvnStackPanel, *mut *mut IAvnControlList) -> i32,
    get_spacing: unsafe extern "system" fn(*mut IAvnStackPanel, *mut f64) -> i32,
    set_spacing: unsafe extern "system" fn(*mut IAvnStackPanel, f64) -> i32,
    get_orientation: unsafe extern "system" fn(*mut IAvnStackPanel, *mut i32) -> i32,
    set_orientation: unsafe extern "system" fn(*mut IAvnStackPanel, i32) -> i32,
}

#[repr(C)]
pub struct IAvnStackPanel {
    vtbl: *const IAvnStackPanelVtbl,
}

unsafe impl ComInterface for IAvnStackPanel {
    const IID: Guid = I_AVN_STACK_PANEL_IID;
}

impl ComPtr<IAvnStackPanel> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
    pub fn get_children(&self) -> Result<ComPtr<IAvnControlList>> {
        unsafe {
            let mut value: *mut IAvnControlList = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_children)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn get_spacing(&self) -> Result<f64> {
        unsafe {
            let mut value: f64 = 0.0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_spacing)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value)
        }
    }
    pub fn set_spacing(&self, value: f64) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_spacing)(self.as_raw(), value);
            hresult::check(hr)
        }
    }
    pub fn get_orientation(&self) -> Result<i32> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_orientation)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value)
        }
    }
    pub fn set_orientation(&self, value: i32) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_orientation)(self.as_raw(), value);
            hresult::check(hr)
        }
    }
}

pub const I_AVN_TEXT_BLOCK_IID: Guid = Guid { data1: 0x4D865988, data2: 0xD36F, data3: 0x53D3, data4: [0x8A, 0xC7, 0x8E, 0xD3, 0x9E, 0xAE, 0x21, 0x68] };

#[repr(C)]
struct IAvnTextBlockVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnTextBlock, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnTextBlock, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnTextBlock, i32) -> i32,
    get_text: unsafe extern "system" fn(*mut IAvnTextBlock, *mut *mut u16) -> i32,
    set_text: unsafe extern "system" fn(*mut IAvnTextBlock, *mut u16) -> i32,
}

#[repr(C)]
pub struct IAvnTextBlock {
    vtbl: *const IAvnTextBlockVtbl,
}

unsafe impl ComInterface for IAvnTextBlock {
    const IID: Guid = I_AVN_TEXT_BLOCK_IID;
}

impl ComPtr<IAvnTextBlock> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
    pub fn get_text(&self) -> Result<*mut u16> {
        unsafe {
            let mut value: *mut u16 = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_text)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value)
        }
    }
    pub fn set_text(&self, value: Option<&[u16]>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_text)(self.as_raw(), value.map_or(ptr::null_mut(), |v| v.as_ptr().cast_mut()));
            hresult::check(hr)
        }
    }
}

pub const I_AVN_WINDOW_IID: Guid = Guid { data1: 0xEC53D901, data2: 0xE166, data3: 0x5DA1, data4: [0xB3, 0x04, 0xE7, 0x6B, 0xC3, 0x71, 0x25, 0xE0] };

#[repr(C)]
struct IAvnWindowVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnWindow, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnWindow, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnWindow, i32) -> i32,
    get_content: unsafe extern "system" fn(*mut IAvnWindow, *mut *mut IAvnControl) -> i32,
    set_content: unsafe extern "system" fn(*mut IAvnWindow, *mut IAvnControl) -> i32,
    get_title: unsafe extern "system" fn(*mut IAvnWindow, *mut *mut u16) -> i32,
    set_title: unsafe extern "system" fn(*mut IAvnWindow, *mut u16) -> i32,
    close: unsafe extern "system" fn(*mut IAvnWindow) -> i32,
    show: unsafe extern "system" fn(*mut IAvnWindow) -> i32,
    show_with_window: unsafe extern "system" fn(*mut IAvnWindow, *mut IAvnWindow) -> i32,
}

#[repr(C)]
pub struct IAvnWindow {
    vtbl: *const IAvnWindowVtbl,
}

unsafe impl ComInterface for IAvnWindow {
    const IID: Guid = I_AVN_WINDOW_IID;
}

impl ComPtr<IAvnWindow> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
    pub fn get_content(&self) -> Result<Option<ComPtr<IAvnControl>>> {
        unsafe {
            let mut value: *mut IAvnControl = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_content)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(ComPtr::from_raw(value))
        }
    }
    pub fn set_content(&self, value: Option<&ComPtr<IAvnControl>>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_content)(self.as_raw(), value.map_or(ptr::null_mut(), ComPtr::as_raw));
            hresult::check(hr)
        }
    }
    pub fn get_title(&self) -> Result<*mut u16> {
        unsafe {
            let mut value: *mut u16 = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_title)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value)
        }
    }
    pub fn set_title(&self, value: Option<&[u16]>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_title)(self.as_raw(), value.map_or(ptr::null_mut(), |v| v.as_ptr().cast_mut()));
            hresult::check(hr)
        }
    }
    pub fn close(&self) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().close)(self.as_raw());
            hresult::check(hr)
        }
    }
    pub fn show(&self) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().show)(self.as_raw());
            hresult::check(hr)
        }
    }
    pub fn show_with_window(&self, owner: &ComPtr<IAvnWindow>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().show_with_window)(self.as_raw(), owner.as_raw());
            hresult::check(hr)
        }
    }
}

pub const IAVN_CONTROL_FACTORY_IID: Guid = Guid { data1: 0xE11331F8, data2: 0x0B6B, data3: 0x5A7C, data4: [0xA1, 0xBB, 0x6D, 0x44, 0x9B, 0xF2, 0x00, 0x70] };

#[repr(C)]
struct IAvnControlFactoryVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    create_avalonia_object: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnAvaloniaObject) -> i32,
    create_button: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnButton) -> i32,
    create_content_control: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnContentControl) -> i32,
    create_control: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnControl) -> i32,
    create_panel: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnPanel) -> i32,
    create_stack_panel: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnStackPanel) -> i32,
    create_text_block: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnTextBlock) -> i32,
    create_window: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnWindow) -> i32,
}

#[repr(C)]
pub struct IAvnControlFactory {
    vtbl: *const IAvnControlFactoryVtbl,
}

unsafe impl ComInterface for IAvnControlFactory {
    const IID: Guid = IAVN_CONTROL_FACTORY_IID;
}

impl ComPtr<IAvnControlFactory> {
    pub fn create_avalonia_object(&self) -> Result<ComPtr<IAvnAvaloniaObject>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_avalonia_object)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_button(&self) -> Result<ComPtr<IAvnButton>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_button)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_content_control(&self) -> Result<ComPtr<IAvnContentControl>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_content_control)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_control(&self) -> Result<ComPtr<IAvnControl>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_control)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_panel(&self) -> Result<ComPtr<IAvnPanel>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_panel)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_stack_panel(&self) -> Result<ComPtr<IAvnStackPanel>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_stack_panel)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_text_block(&self) -> Result<ComPtr<IAvnTextBlock>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_text_block)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_window(&self) -> Result<ComPtr<IAvnWindow>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_window)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
}
