//! Generated by avalonia-bindgen. Do not edit.
#![allow(dead_code, non_snake_case)]

use crate::com::{ComInterface, ComPtr, IUnknown};
use crate::guid::Guid;
use crate::hresult::{self, Error, Result};
use std::ffi::c_void;
use std::ptr;

pub const I_AVN_CONTROL_LIST_IID: Guid = Guid { data1: 0x4CBDF266, data2: 0x1DCD, data3: 0x58C5, data4: [0xB1, 0xE5, 0xAE, 0x74, 0xCF, 0x5B, 0x42, 0x2A] };

#[repr(C)]
struct IAvnControlListVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_count: unsafe extern "system" fn(*mut IAvnControlList, *mut i32) -> i32,
    get_at: unsafe extern "system" fn(*mut IAvnControlList, i32, *mut *mut IAvnControl) -> i32,
    add: unsafe extern "system" fn(*mut IAvnControlList, *mut IAvnControl) -> i32,
    remove_at: unsafe extern "system" fn(*mut IAvnControlList, i32) -> i32,
    clear: unsafe extern "system" fn(*mut IAvnControlList) -> i32,
}

#[repr(C)]
pub struct IAvnControlList {
    vtbl: *const IAvnControlListVtbl,
}

unsafe impl ComInterface for IAvnControlList {
    const IID: Guid = I_AVN_CONTROL_LIST_IID;
}

impl ComPtr<IAvnControlList> {
    pub fn len(&self) -> Result<usize> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_count)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value as usize)
        }
    }
    pub fn get(&self, index: usize) -> Result<ComPtr<IAvnControl>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_at)(self.as_raw(), index as i32, &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn add(&self, value: &ComPtr<IAvnControl>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().add)(self.as_raw(), value.as_raw());
            hresult::check(hr)
        }
    }
    pub fn remove(&self, index: usize) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().remove_at)(self.as_raw(), index as i32);
            hresult::check(hr)
        }
    }
    pub fn clear(&self) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().clear)(self.as_raw());
            hresult::check(hr)
        }
    }
}

pub const I_AVN_AVALONIA_OBJECT_IID: Guid = Guid { data1: 0x57D5FB2B, data2: 0xED86, data3: 0x525C, data4: [0xB6, 0x5D, 0x49, 0x8A, 0x84, 0xC7, 0x5A, 0xFA] };

#[repr(C)]
struct IAvnAvaloniaObjectVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnAvaloniaObject, *mut i64) -> i32,
}

#[repr(C)]
pub struct IAvnAvaloniaObject {
    vtbl: *const IAvnAvaloniaObjectVtbl,
}

unsafe impl ComInterface for IAvnAvaloniaObject {
    const IID: Guid = I_AVN_AVALONIA_OBJECT_IID;
}

impl ComPtr<IAvnAvaloniaObject> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
}

pub const I_AVN_BUTTON_IID: Guid = Guid { data1: 0x0E740E4A, data2: 0xA102, data3: 0x5ADB, data4: [0xA6, 0x3F, 0x80, 0x22, 0xBA, 0x7E, 0xBF, 0x9D] };

#[repr(C)]
struct IAvnButtonVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnButton, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnButton, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnButton, i32) -> i32,
    get_content: unsafe extern "system" fn(*mut IAvnButton, *mut *mut IAvnControl) -> i32,
    set_content: unsafe extern "system" fn(*mut IAvnButton, *mut IAvnControl) -> i32,
}

#[repr(C)]
pub struct IAvnButton {
    vtbl: *const IAvnButtonVtbl,
}

unsafe impl ComInterface for IAvnButton {
    const IID: Guid = I_AVN_BUTTON_IID;
}

impl ComPtr<IAvnButton> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
    pub fn get_content(&self) -> Result<Option<ComPtr<IAvnControl>>> {
        unsafe {
            let mut value: *mut IAvnControl = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_content)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(ComPtr::from_raw(value))
        }
    }
    pub fn set_content(&self, value: Option<&ComPtr<IAvnControl>>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_content)(self.as_raw(), value.map_or(ptr::null_mut(), ComPtr::as_raw));
            hresult::check(hr)
        }
    }
}

pub const I_AVN_CONTENT_CONTROL_IID: Guid = Guid { data1: 0x503C621A, data2: 0x9937, data3: 0x5F82, data4: [0xB5, 0x80, 0x0D, 0x72, 0xD6, 0x78, 0x1E, 0xE8] };

#[repr(C)]
struct IAvnContentControlVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnContentControl, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnContentControl, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnContentControl, i32) -> i32,
    get_content: unsafe extern "system" fn(*mut IAvnContentControl, *mut *mut IAvnControl) -> i32,
    set_content: unsafe extern "system" fn(*mut IAvnContentControl, *mut IAvnControl) -> i32,
}

#[repr(C)]
pub struct IAvnContentControl {
    vtbl: *const IAvnContentControlVtbl,
}

unsafe impl ComInterface for IAvnContentControl {
    const IID: Guid = I_AVN_CONTENT_CONTROL_IID;
}

impl ComPtr<IAvnContentControl> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
    pub fn get_content(&self) -> Result<Option<ComPtr<IAvnControl>>> {
        unsafe {
            let mut value: *mut IAvnControl = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_content)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(ComPtr::from_raw(value))
        }
    }
    pub fn set_content(&self, value: Option<&ComPtr<IAvnControl>>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_content)(self.as_raw(), value.map_or(ptr::null_mut(), ComPtr::as_raw));
            hresult::check(hr)
        }
    }
}

pub const I_AVN_CONTROL_IID: Guid = Guid { data1: 0x2030D5A1, data2: 0xE324, data3: 0x559C, data4: [0x98, 0xBD, 0x99, 0x80, 0x4D, 0x62, 0x26, 0x15] };

#[repr(C)]
struct IAvnControlVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnControl, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnControl, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnControl, i32) -> i32,
}

#[repr(C)]
pub struct IAvnControl {
    vtbl: *const IAvnControlVtbl,
}

unsafe impl ComInterface for IAvnControl {
    const IID: Guid = I_AVN_CONTROL_IID;
}

impl ComPtr<IAvnControl> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
}

pub const I_AVN_PANEL_IID: Guid = Guid { data1: 0x1BDD67C1, data2: 0x5AB4, data3: 0x5AC5, data4: [0xA8, 0x65, 0xA6, 0x84, 0x76, 0xA4, 0x22, 0x7B] };

#[repr(C)]
struct IAvnPanelVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnPanel, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnPanel, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnPanel, i32) -> i32,
    get_children: unsafe extern "system" fn(*mut IAvnPanel, *mut *mut IAvnControlList) -> i32,
}

#[repr(C)]
pub struct IAvnPanel {
    vtbl: *const IAvnPanelVtbl,
}

unsafe impl ComInterface for IAvnPanel {
    const IID: Guid = I_AVN_PANEL_IID;
}

impl ComPtr<IAvnPanel> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
    pub fn get_children(&self) -> Result<ComPtr<IAvnControlList>> {
        unsafe {
            let mut value: *mut IAvnControlList = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_children)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
}

pub const I_AVN_STACK_PANEL_IID: Guid = Guid { data1: 0x8B8C126D, data2: 0x9D75, data3: 0x5542, data4: [0x83, 0xA3, 0xA7, 0x22, 0x4D, 0x3C, 0x0C, 0x6D] };

#[repr(C)]
struct IAvnStackPanelVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnStackPanel, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnStackPanel, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnStackPanel, i32) -> i32,
    get_children: unsafe extern "system" fn(*mut IAvnStackPanel, *mut *mut IAvnControlList) -> i32,
    get_spacing: unsafe extern "system" fn(*mut IAvnStackPanel, *mut f64) -> i32,
    set_spacing: unsafe extern "system" fn(*mut IAvnStackPanel, f64) -> i32,
    get_orientation: unsafe extern "system" fn(*mut IAvnStackPanel, *mut i32) -> i32,
    set_orientation: unsafe extern "system" fn(*mut IAvnStackPanel, i32) -> i32,
}

#[repr(C)]
pub struct IAvnStackPanel {
    vtbl: *const IAvnStackPanelVtbl,
}

unsafe impl ComInterface for IAvnStackPanel {
    const IID: Guid = I_AVN_STACK_PANEL_IID;
}

impl ComPtr<IAvnStackPanel> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
    pub fn get_children(&self) -> Result<ComPtr<IAvnControlList>> {
        unsafe {
            let mut value: *mut IAvnControlList = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_children)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn get_spacing(&self) -> Result<f64> {
        unsafe {
            let mut value: f64 = 0.0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_spacing)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value)
        }
    }
    pub fn set_spacing(&self, value: f64) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_spacing)(self.as_raw(), value);
            hresult::check(hr)
        }
    }
    pub fn get_orientation(&self) -> Result<i32> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_orientation)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value)
        }
    }
    pub fn set_orientation(&self, value: i32) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_orientation)(self.as_raw(), value);
            hresult::check(hr)
        }
    }
}

pub const I_AVN_TEXT_BLOCK_IID: Guid = Guid { data1: 0xEB7ECAEC, data2: 0xC3EB, data3: 0x5A23, data4: [0x85, 0x0C, 0x28, 0xB7, 0xA5, 0xCA, 0x67, 0x9B] };

#[repr(C)]
struct IAvnTextBlockVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnTextBlock, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnTextBlock, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnTextBlock, i32) -> i32,
    get_text: unsafe extern "system" fn(*mut IAvnTextBlock, *mut *mut u16) -> i32,
    set_text: unsafe extern "system" fn(*mut IAvnTextBlock, *mut u16) -> i32,
}

#[repr(C)]
pub struct IAvnTextBlock {
    vtbl: *const IAvnTextBlockVtbl,
}

unsafe impl ComInterface for IAvnTextBlock {
    const IID: Guid = I_AVN_TEXT_BLOCK_IID;
}

impl ComPtr<IAvnTextBlock> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
    pub fn get_text(&self) -> Result<*mut u16> {
        unsafe {
            let mut value: *mut u16 = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_text)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value)
        }
    }
    pub fn set_text(&self, value: Option<&[u16]>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_text)(self.as_raw(), value.map_or(ptr::null_mut(), |v| v.as_ptr().cast_mut()));
            hresult::check(hr)
        }
    }
}

pub const I_AVN_WINDOW_IID: Guid = Guid { data1: 0x178A1A08, data2: 0xF7D2, data3: 0x5383, data4: [0xA8, 0x5F, 0x53, 0x15, 0x9C, 0xE7, 0x28, 0xB1] };

#[repr(C)]
struct IAvnWindowVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    get_object_id: unsafe extern "system" fn(*mut IAvnWindow, *mut i64) -> i32,
    get_is_enabled: unsafe extern "system" fn(*mut IAvnWindow, *mut i32) -> i32,
    set_is_enabled: unsafe extern "system" fn(*mut IAvnWindow, i32) -> i32,
    get_content: unsafe extern "system" fn(*mut IAvnWindow, *mut *mut IAvnControl) -> i32,
    set_content: unsafe extern "system" fn(*mut IAvnWindow, *mut IAvnControl) -> i32,
    get_title: unsafe extern "system" fn(*mut IAvnWindow, *mut *mut u16) -> i32,
    set_title: unsafe extern "system" fn(*mut IAvnWindow, *mut u16) -> i32,
    close: unsafe extern "system" fn(*mut IAvnWindow) -> i32,
    show: unsafe extern "system" fn(*mut IAvnWindow) -> i32,
    show_with_window: unsafe extern "system" fn(*mut IAvnWindow, *mut IAvnWindow) -> i32,
}

#[repr(C)]
pub struct IAvnWindow {
    vtbl: *const IAvnWindowVtbl,
}

unsafe impl ComInterface for IAvnWindow {
    const IID: Guid = I_AVN_WINDOW_IID;
}

impl ComPtr<IAvnWindow> {
    pub fn object_id(&self) -> Result<i64> {
        unsafe {
            let mut value = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);
            hresult::check(hr).map(|_| value)
        }
    }
    pub fn get_is_enabled(&self) -> Result<bool> {
        unsafe {
            let mut value: i32 = 0;
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_is_enabled)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value != 0)
        }
    }
    pub fn set_is_enabled(&self, value: bool) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_is_enabled)(self.as_raw(), i32::from(value));
            hresult::check(hr)
        }
    }
    pub fn get_content(&self) -> Result<Option<ComPtr<IAvnControl>>> {
        unsafe {
            let mut value: *mut IAvnControl = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_content)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(ComPtr::from_raw(value))
        }
    }
    pub fn set_content(&self, value: Option<&ComPtr<IAvnControl>>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_content)(self.as_raw(), value.map_or(ptr::null_mut(), ComPtr::as_raw));
            hresult::check(hr)
        }
    }
    pub fn get_title(&self) -> Result<*mut u16> {
        unsafe {
            let mut value: *mut u16 = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_title)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            Ok(value)
        }
    }
    pub fn set_title(&self, value: Option<&[u16]>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_title)(self.as_raw(), value.map_or(ptr::null_mut(), |v| v.as_ptr().cast_mut()));
            hresult::check(hr)
        }
    }
    pub fn close(&self) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().close)(self.as_raw());
            hresult::check(hr)
        }
    }
    pub fn show(&self) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().show)(self.as_raw());
            hresult::check(hr)
        }
    }
    pub fn show_with_window(&self, owner: &ComPtr<IAvnWindow>) -> Result<()> {
        unsafe {
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().show_with_window)(self.as_raw(), owner.as_raw());
            hresult::check(hr)
        }
    }
}

pub const IAVN_CONTROL_FACTORY_IID: Guid = Guid { data1: 0x2B245C89, data2: 0xD703, data3: 0x54E1, data4: [0x91, 0x4F, 0x58, 0x68, 0x3E, 0xFF, 0xD2, 0xC8] };

#[repr(C)]
struct IAvnControlFactoryVtbl {
    query_interface: unsafe extern "system" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
    add_ref: unsafe extern "system" fn(*mut IUnknown) -> u32,
    release: unsafe extern "system" fn(*mut IUnknown) -> u32,
    create_avalonia_object: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnAvaloniaObject) -> i32,
    create_button: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnButton) -> i32,
    create_content_control: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnContentControl) -> i32,
    create_control: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnControl) -> i32,
    create_panel: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnPanel) -> i32,
    create_stack_panel: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnStackPanel) -> i32,
    create_text_block: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnTextBlock) -> i32,
    create_window: unsafe extern "system" fn(*mut IAvnControlFactory, *mut *mut IAvnWindow) -> i32,
}

#[repr(C)]
pub struct IAvnControlFactory {
    vtbl: *const IAvnControlFactoryVtbl,
}

unsafe impl ComInterface for IAvnControlFactory {
    const IID: Guid = IAVN_CONTROL_FACTORY_IID;
}

impl ComPtr<IAvnControlFactory> {
    pub fn create_avalonia_object(&self) -> Result<ComPtr<IAvnAvaloniaObject>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_avalonia_object)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_button(&self) -> Result<ComPtr<IAvnButton>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_button)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_content_control(&self) -> Result<ComPtr<IAvnContentControl>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_content_control)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_control(&self) -> Result<ComPtr<IAvnControl>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_control)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_panel(&self) -> Result<ComPtr<IAvnPanel>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_panel)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_stack_panel(&self) -> Result<ComPtr<IAvnStackPanel>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_stack_panel)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_text_block(&self) -> Result<ComPtr<IAvnTextBlock>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_text_block)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
    pub fn create_window(&self) -> Result<ComPtr<IAvnWindow>> {
        unsafe {
            let mut value = ptr::null_mut();
            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_window)(self.as_raw(), &mut value);
            hresult::check(hr)?;
            ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))
        }
    }
}
