use crate::ir::{ProjectedMethod, ProjectedParameter, ProjectedType, ProjectionIr};

pub fn emit_sys_module(ir: &ProjectionIr) -> String {
    let mut out = String::from(
        "//! Generated by avalonia-bindgen. Do not edit.\n\
         #![allow(dead_code, non_snake_case)]\n\n\
         use crate::com::{ComInterface, ComPtr, IUnknown};\n\
         use crate::guid::Guid;\n\
         use crate::hresult::{self, Result};\n\
         use std::ffi::c_void;\n\
         use std::ptr;\n\n",
    );
    for ty in ir.types.iter().filter(|t| t.kind == "Interface") {
        out.push_str(&emit_interface(ty));
        out.push('\n');
    }
    out
}

fn emit_interface(ty: &ProjectedType) -> String {
    let mut s = String::new();
    let iid_const = format!("{}_IID", to_shouty(&ty.name));
    if let Some(iid) = &ty.iid {
        s.push_str(&format!("pub const {iid_const}: Guid = {};\n\n", guid_literal(iid)));
    }

    s.push_str("#[repr(C)]\n");
    s.push_str(&format!("struct {}Vtbl {{\n", ty.name));
    s.push_str("    query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n");
    s.push_str("    add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n");
    s.push_str("    release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n");
    for method in &ty.methods {
        s.push_str(&format!(
            "    {}: unsafe extern \"system\" fn({}\n",
            to_snake(&method.name),
            vtbl_fn_sig(ty, method)
        ));
    }
    s.push_str("}\n\n");

    s.push_str("#[repr(C)]\n");
    s.push_str(&format!("pub struct {} {{\n    vtbl: *const {}Vtbl,\n}}\n\n", ty.name, ty.name));
    s.push_str(&format!("unsafe impl ComInterface for {} {{\n", ty.name));
    if ty.iid.is_some() {
        s.push_str(&format!("    const IID: Guid = {iid_const};\n"));
    }
    s.push_str("}\n\n");

    s.push_str(&format!("impl ComPtr<{}> {{\n", ty.name));
    for method in &ty.methods {
        s.push_str(&emit_method(ty, method));
    }
    s.push_str("}\n");
    s
}

fn emit_method(_ty: &ProjectedType, method: &ProjectedMethod) -> String {
    let snake = to_snake(&method.name);
    let rust_args = method
        .parameters
        .iter()
        .filter(|p| p.direction != "Out")
        .map(|p| format!(", {}: {}", to_snake(&p.name), rust_in_type(p)))
        .collect::<String>();
    let out_params: Vec<_> = method.parameters.iter().filter(|p| p.direction == "Out").collect();

    let mut body = String::new();
    for p in &out_params {
        body.push_str(&format!(
            "            let mut {} = {};\n",
            to_snake(&p.name),
            rust_out_default(p)
        ));
    }
    let call_args = method
        .parameters
        .iter()
        .map(|p| {
            if p.direction == "Out" {
                format!("&mut {}", to_snake(&p.name))
            } else if p.kind == "StringUtf16" {
                format!("{}.as_ptr()", to_snake(&p.name))
            } else {
                to_snake(&p.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let extra = if call_args.is_empty() {
        String::new()
    } else {
        format!(", {call_args}")
    };

    body.push_str(&format!(
        "            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().{snake})(self.as_raw(){extra});\n"
    ));

    let ret = if out_params.len() == 1 {
        format!("hresult::check(hr).map(|_| {})", to_snake(&out_params[0].name))
    } else if out_params.is_empty() {
        "hresult::check(hr)".to_string()
    } else {
        let names = out_params
            .iter()
            .map(|p| to_snake(&p.name))
            .collect::<Vec<_>>()
            .join(", ");
        format!("hresult::check(hr).map(|_| ({names}))")
    };

    format!(
        "    pub fn {snake}(&self{rust_args}) -> Result<{}> {{\n        unsafe {{\n{body}            {ret}\n        }}\n    }}\n",
        rust_result_type(&out_params),
    )
}

fn vtbl_fn_sig(ty: &ProjectedType, method: &ProjectedMethod) -> String {
    let mut args = vec![format!("*mut {}", ty.name)];
    for p in &method.parameters {
        args.push(vtbl_param_ty(p));
    }
    format!("{}) -> i32,\n", args.join(", "))
}

fn vtbl_param_ty(p: &ProjectedParameter) -> String {
    let inner = match p.kind.as_str() {
        "I32" => "i32",
        "I64" => "i64",
        "F32" => "f32",
        "F64" => "f64",
        "Bool" => "i32",
        "StringUtf16" => "*mut u16",
        "ComInterface" => "*mut c_void",
        _ => "c_void",
    };
    if p.direction == "Out" {
        format!("*mut {inner}")
    } else if p.kind == "StringUtf16" {
        "*const u16".into()
    } else {
        inner.into()
    }
}

fn rust_in_type(p: &ProjectedParameter) -> &'static str {
    match p.kind.as_str() {
        "I32" => "i32",
        "I64" => "i64",
        "F32" => "f32",
        "F64" => "f64",
        "Bool" => "bool",
        "StringUtf16" => "&[u16]",
        "ComInterface" => "*mut c_void",
        _ => "()",
    }
}

fn rust_out_default(p: &ProjectedParameter) -> &'static str {
    match p.kind.as_str() {
        "I32" | "I64" | "F32" | "F64" => "0",
        _ => "ptr::null_mut()",
    }
}

fn rust_result_type(out_params: &[&ProjectedParameter]) -> String {
    match out_params.len() {
        0 => "()".into(),
        1 => rust_out_ty(out_params[0]).into(),
        _ => format!(
            "({})",
            out_params.iter().map(|p| rust_out_ty(p)).collect::<Vec<_>>().join(", ")
        ),
    }
}

fn rust_out_ty(p: &ProjectedParameter) -> &'static str {
    match p.kind.as_str() {
        "I32" => "i32",
        "I64" => "i64",
        "F32" => "f32",
        "F64" => "f64",
        "Bool" => "bool",
        "StringUtf16" => "*mut u16",
        "ComInterface" => "*mut c_void",
        _ => "()",
    }
}

fn guid_literal(iid: &str) -> String {
    let parts: Vec<&str> = iid.split('-').collect();
    if parts.len() != 5 {
        return "Guid::IUNKNOWN".into();
    }
    let d4 = parts[3].to_string() + parts[4];
    let bytes: Vec<String> = (0..8)
        .map(|i| format!("0x{}", &d4[i * 2..i * 2 + 2]))
        .collect();
    format!(
        "Guid {{ data1: 0x{}, data2: 0x{}, data3: 0x{}, data4: [{}] }}",
        parts[0],
        parts[1],
        parts[2],
        bytes.join(", ")
    )
}

fn to_snake(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

fn to_shouty(name: &str) -> String {
    to_snake(name).to_uppercase()
}
