use crate::geometry;
use crate::ir::{
    ProjectedAttachedProperty, ProjectedEvent, ProjectedMethod, ProjectedParameter,
    ProjectedProperty, ProjectedType, ProjectionIr,
};

pub fn emit_sys_module(ir: &ProjectionIr) -> String {
    let mut out = String::from(
        "//! Generated by avalonia-bindgen. Do not edit.\n\
         #![allow(dead_code, non_snake_case)]\n\n\
         use crate::com::{ComInterface, ComPtr, IUnknown};\n\
         use crate::guid::Guid;\n\
         use crate::hresult::{self, Error, Result};\n\
         use std::ffi::c_void;\n\
         use std::ptr;\n\n",
    );
    out.push_str(&geometry::emit_sys_structs());
    if ir.brush_interface_name.is_some() {
        out.push_str(&emit_brush(ir));
        out.push('\n');
    }
    for event in unique_events(ir) {
        out.push_str(&emit_event_handler(event));
        out.push('\n');
    }
    let mut emitted_collections = Vec::new();
    for collection in ir
        .types
        .iter()
        .flat_map(|t| t.properties.iter())
        .filter(|p| p.kind == "ComCollection")
    {
        let name = collection
            .interface_name
            .as_deref()
            .expect("collection interfaceName");
        if !emitted_collections.contains(&name) {
            out.push_str(&emit_collection(collection));
            out.push('\n');
            emitted_collections.push(name);
        }
    }
    for ty in ir
        .types
        .iter()
        .filter(|t| t.kind == "Interface" || t.kind == "Class")
    {
        out.push_str(&emit_interface(ir, ty));
        out.push('\n');
    }
    for properties in attached_property_groups(ir) {
        out.push_str(&emit_attached_statics(&properties));
        out.push('\n');
    }
    if ir.types.iter().any(|t| t.is_constructible) {
        out.push_str(&emit_factory(ir));
    }
    out
}

fn emit_collection(collection: &ProjectedProperty) -> String {
    let interface_name = simple_name(
        collection
            .interface_name
            .as_deref()
            .expect("collection interfaceName"),
    );
    let element_kind = collection
        .element_kind
        .as_deref()
        .expect("collection elementKind");
    let element_name = collection
        .element_interface_name
        .as_deref()
        .map(simple_name);
    let abi_type = rust_abi_type(element_kind, collection.element_interface_name.as_deref());
    let iid = collection
        .interface_iid
        .as_deref()
        .expect("collection interfaceIid");
    let iid_const = format!("{}_IID", to_shouty(interface_name));
    let mut out = format!(
        "pub const {iid_const}: Guid = {iid};\n\n\
         #[repr(C)]\n\
         struct {interface_name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   get_count: unsafe extern \"system\" fn(*mut {interface_name}, *mut i32) -> i32,\n\
         \x20   get_at: unsafe extern \"system\" fn(*mut {interface_name}, i32, *mut {abi_type}) -> i32,\n\
         \x20   add: unsafe extern \"system\" fn(*mut {interface_name}, {abi_type}) -> i32,\n\
         \x20   index_of: unsafe extern \"system\" fn(*mut {interface_name}, {abi_type}, *mut i32) -> i32,\n\
         \x20   remove_at: unsafe extern \"system\" fn(*mut {interface_name}, i32) -> i32,\n\
         \x20   clear: unsafe extern \"system\" fn(*mut {interface_name}) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {interface_name} {{\n\
         \x20   vtbl: *const {interface_name}Vtbl,\n\
         }}\n\n\
         unsafe impl ComInterface for {interface_name} {{\n\
         \x20   const IID: Guid = {iid_const};\n\
         }}\n\n\
         impl ComPtr<{interface_name}> {{\n\
         \x20   pub fn len(&self) -> Result<usize> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut value = 0;\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_count)(self.as_raw(), &mut value);\n\
         \x20           hresult::check(hr).map(|_| value as usize)\n\
         \x20       }}\n\
         \x20   }}\n\
        \x20   pub fn is_empty(&self) -> Result<bool> {{\n\
        \x20       Ok(self.len()? == 0)\n\
        \x20   }}\n\
",
        iid = guid_literal(iid)
    );
    match element_kind {
        "ComInterface" => {
            let element_name = element_name.expect("COM collection elementInterfaceName");
            out.push_str(&format!(
                "    pub fn get(&self, index: usize) -> Result<ComPtr<{element_name}>> {{\n\
                 \x20       unsafe {{\n\
                 \x20           let mut value = ptr::null_mut();\n\
                 \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_at)(self.as_raw(), index as i32, &mut value);\n\
                 \x20           hresult::check(hr)?;\n\
                 \x20           ComPtr::from_projected_raw(value)\n\
                 \x20       }}\n\
                 \x20   }}\n\
                 \x20   pub fn add(&self, value: &ComPtr<{element_name}>) -> Result<()> {{\n\
                 \x20       unsafe {{ hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().add)(self.as_raw(), value.as_raw())) }}\n\
                 \x20   }}\n\
                 \x20   pub fn index_of(&self, value: &ComPtr<{element_name}>) -> Result<Option<usize>> {{\n\
                 \x20       unsafe {{\n\
                 \x20           let mut index = -1;\n\
                 \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().index_of)(self.as_raw(), value.as_raw(), &mut index);\n\
                 \x20           hresult::check(hr).map(|_| (index >= 0).then_some(index as usize))\n\
                 \x20       }}\n\
                 \x20   }}\n"
            ));
        }
        "StringUtf16" => out.push_str(
            "    pub fn get(&self, index: usize) -> Result<*mut u16> {\n\
             \x20       unsafe {\n\
             \x20           let mut value = ptr::null_mut();\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_at)(self.as_raw(), index as i32, &mut value);\n\
             \x20           hresult::check(hr).map(|_| value)\n\
             \x20       }\n\
             \x20   }\n\
             \x20   pub fn add(&self, value: &[u16]) -> Result<()> {\n\
             \x20       unsafe { hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().add)(self.as_raw(), value.as_ptr().cast_mut())) }\n\
             \x20   }\n\
             \x20   pub fn index_of(&self, value: &[u16]) -> Result<Option<usize>> {\n\
             \x20       unsafe {\n\
             \x20           let mut index = -1;\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().index_of)(self.as_raw(), value.as_ptr().cast_mut(), &mut index);\n\
             \x20           hresult::check(hr).map(|_| (index >= 0).then_some(index as usize))\n\
             \x20       }\n\
             \x20   }\n",
        ),
        _ => panic!("unsupported collection element kind {element_kind}"),
    }
    out.push_str(
        "    pub fn remove(&self, index: usize) -> Result<()> {\n\
         \x20       unsafe { hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().remove_at)(self.as_raw(), index as i32)) }\n\
         \x20   }\n\
         \x20   pub fn clear(&self) -> Result<()> {\n\
         \x20       unsafe { hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().clear)(self.as_raw())) }\n\
         \x20   }\n\
         }\n",
    );
    out
}

fn emit_brush(ir: &ProjectionIr) -> String {
    let name = simple_name(
        ir.brush_interface_name
            .as_deref()
            .expect("brushInterfaceName"),
    );
    let iid = ir
        .brush_interface_iid
        .as_deref()
        .expect("brushInterfaceIid for a projected brush");
    let iid_const = format!("{}_IID", to_shouty(name));
    let color = geometry::find("Color")
        .expect("Color geometry struct")
        .abi_name;
    format!(
        "/// A brush projected as a solid colour: a packed `{color}` plus an opacity.\n\
         ///\n\
         /// Read-only: the managed side hands out immutable brushes, so a new brush is minted\n\
         /// through `IAvnControlFactory::create_solid_color_brush`. Reading a gradient, drawing\n\
         /// or visual brush fails rather than degrading to a nearest colour.\n\
         pub const {iid_const}: Guid = {iid_literal};\n\n\
         #[repr(C)]\n\
         struct {name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   get_color: unsafe extern \"system\" fn(*mut {name}, *mut {color}) -> i32,\n\
         \x20   get_opacity: unsafe extern \"system\" fn(*mut {name}, *mut f64) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {name} {{\n\
         \x20   vtbl: *const {name}Vtbl,\n\
         }}\n\n\
         unsafe impl ComInterface for {name} {{\n\
         \x20   const IID: Guid = {iid_const};\n\
         }}\n\n\
         impl ComPtr<{name}> {{\n\
         \x20   pub fn color(&self) -> Result<{color}> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut value: {color} = Default::default();\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_color)(self.as_raw(), &mut value);\n\
         \x20           hresult::check(hr).map(|_| value)\n\
         \x20       }}\n\
         \x20   }}\n\
         \x20   pub fn opacity(&self) -> Result<f64> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut value = 0.0;\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_opacity)(self.as_raw(), &mut value);\n\
         \x20           hresult::check(hr).map(|_| value)\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n",
        iid_literal = guid_literal(iid)
    )
}

fn emit_interface(ir: &ProjectionIr, ty: &ProjectedType) -> String {
    let mut out = String::new();
    let iid_const = format!("{}_IID", to_shouty(&ty.name));
    if let Some(iid) = &ty.iid {
        out.push_str(&format!(
            "pub const {iid_const}: Guid = {};\n\n",
            guid_literal(iid)
        ));
    }

    out.push_str("#[repr(C)]\n");
    out.push_str(&format!("struct {}Vtbl {{\n", ty.name));
    emit_iunknown_slots(&mut out);
    if ty.kind == "Class" {
        out.push_str(&format!(
            "    get_object_id: unsafe extern \"system\" fn(*mut {}, *mut i64) -> i32,\n\
             \x20   get_lifetime_token: unsafe extern \"system\" fn(*mut {}, *mut i64) -> i32,\n",
            ty.name, ty.name
        ));
    }
    for owner in lineage(ir, ty) {
        for property in &owner.properties {
            emit_property_slots(&mut out, ty, property);
        }
        for method in &owner.methods {
            out.push_str(&format!(
                "    {}: unsafe extern \"system\" fn({}) -> i32,\n",
                to_snake(&method.name),
                vtbl_method_args(ty, method)
            ));
        }
        for event in &owner.events {
            let handler = simple_name(&event.handler_interface_name);
            let snake = to_snake(&event.name);
            out.push_str(&format!(
                "    advise_{snake}: unsafe extern \"system\" fn(*mut {}, *mut {handler}, *mut i64) -> i32,\n\
                 \x20   unadvise_{snake}: unsafe extern \"system\" fn(*mut {}, i64) -> i32,\n",
                ty.name, ty.name
            ));
        }
    }
    out.push_str("}\n\n");

    out.push_str("#[repr(C)]\n");
    out.push_str(&format!(
        "pub struct {} {{\n    vtbl: *const {}Vtbl,\n}}\n\n",
        ty.name, ty.name
    ));
    out.push_str(&format!("unsafe impl ComInterface for {} {{\n", ty.name));
    if ty.iid.is_some() {
        out.push_str(&format!("    const IID: Guid = {iid_const};\n"));
    }
    out.push_str("}\n\n");

    out.push_str(&format!("impl ComPtr<{}> {{\n", ty.name));
    if ty.kind == "Class" {
        out.push_str(
            "    pub fn object_id(&self) -> Result<i64> {\n\
             \x20       unsafe {\n\
             \x20           let mut value = 0;\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);\n\
             \x20           hresult::check(hr).map(|_| value)\n\
             \x20       }\n\
             \x20   }\n",
        );
        out.push_str(
            "    pub fn lifetime_token(&self) -> Result<*mut IUnknown> {\n\
             \x20       unsafe {\n\
             \x20           let mut value = 0i64;\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_lifetime_token)(self.as_raw(), &mut value);\n\
             \x20           hresult::check(hr).map(|_| value as usize as *mut IUnknown)\n\
             \x20       }\n\
             \x20   }\n",
        );
    }
    for owner in lineage(ir, ty) {
        for property in &owner.properties {
            out.push_str(&emit_property(ty, property));
        }
        for method in &owner.methods {
            out.push_str(&emit_method(ty, method));
        }
        for event in &owner.events {
            out.push_str(&emit_event(event));
        }
    }

    out.push_str("}\n");
    out
}

fn emit_event_handler(event: &ProjectedEvent) -> String {
    if !event.parameters.is_empty() {
        return emit_field_event_handler(event);
    }
    assert_eq!(event.payload_kind, "None", "unsupported event payload kind");
    let name = simple_name(&event.handler_interface_name);
    let iid_const = format!("{}_IID", to_shouty(name));
    let stem = to_snake(name);
    format!(
        "pub const {iid_const}: Guid = {iid};\n\n\
         #[repr(C)]\n\
         struct {name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   invoke: unsafe extern \"system\" fn(*mut {name}) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {name} {{\n\
         \x20   vtbl: *const {name}Vtbl,\n\
         }}\n\n\
         unsafe impl ComInterface for {name} {{\n\
         \x20   const IID: Guid = {iid_const};\n\
         }}\n\n\
         impl ComPtr<{name}> {{\n\
         \x20   pub fn invoke(&self) -> Result<()> {{\n\
         \x20       unsafe {{\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().invoke)(self.as_raw());\n\
         \x20           hresult::check(hr)\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n\n\
         static {shouty}_VTBL: {name}Vtbl = {name}Vtbl {{\n\
         \x20   query_interface: {stem}_query_interface,\n\
         \x20   add_ref: {stem}_add_ref,\n\
         \x20   release: {stem}_release,\n\
         \x20   invoke: {stem}_invoke,\n\
         }};\n\n\
         pub fn {handler_fn}(mut callback: impl FnMut() -> Result<()> + Send + 'static) -> ComPtr<{name}> {{\n\
         \x20   crate::event_callback::create::<{name}, ()>({name} {{ vtbl: &{shouty}_VTBL }}, move |_| callback())\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_query_interface(this: *mut IUnknown, iid: *const Guid, result: *mut *mut c_void) -> i32 {{\n\
         \x20   crate::event_callback::query_interface::<{name}, ()>(this, iid, result)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_add_ref(this: *mut IUnknown) -> u32 {{\n\
         \x20   crate::event_callback::add_ref::<{name}, ()>(this)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_release(this: *mut IUnknown) -> u32 {{\n\
         \x20   crate::event_callback::release::<{name}, ()>(this)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_invoke(this: *mut {name}) -> i32 {{\n\
         \x20   crate::event_callback::invoke::<{name}, ()>(this, &mut ())\n\
         }}\n",
        iid = guid_literal(&event.handler_interface_iid),
        shouty = to_shouty(name),
        handler_fn = event_handler_function(event),
    )
}

fn emit_field_event_handler(event: &ProjectedEvent) -> String {
    assert_eq!(
        event.payload_kind, "Fields",
        "parameterized events require Fields payload kind"
    );
    let name = simple_name(&event.handler_interface_name);
    let iid_const = format!("{}_IID", to_shouty(name));
    let shouty = to_shouty(name);
    let stem = to_snake(name);
    let args_name = format!(
        "{}EventArgs",
        name.strip_prefix("IAvn")
            .unwrap_or(name)
            .strip_suffix("Handler")
            .unwrap_or(name)
    );
    let parameters = event
        .parameters
        .iter()
        .map(|parameter| {
            let abi = rust_abi_type(&parameter.kind, parameter.interface_name.as_deref());
            if parameter.direction == "InOut" {
                format!(", {}: *mut {abi}", to_snake(&parameter.name))
            } else {
                format!(", {}: {abi}", to_snake(&parameter.name))
            }
        })
        .collect::<String>();
    let fields = event
        .parameters
        .iter()
        .map(|parameter| {
            format!(
                "    pub {}: {},\n",
                to_snake(&parameter.name),
                event_argument_type(parameter)
            )
        })
        .collect::<String>();
    let null_checks = event
        .parameters
        .iter()
        .filter(|parameter| parameter.direction == "InOut")
        .map(|parameter| {
            format!(
                "    if {}.is_null() {{ return hresult::E_POINTER; }}\n",
                to_snake(&parameter.name)
            )
        })
        .collect::<String>();
    let initializers = event
        .parameters
        .iter()
        .map(|parameter| {
            let name = to_snake(&parameter.name);
            let source = match (parameter.kind.as_str(), parameter.direction.as_str()) {
                ("Bool", "InOut") => format!("*{name} != 0"),
                ("Bool", _) => format!("{name} != 0"),
                ("StringUtf16", _) => format!("crate::clone_utf16({name})"),
                (_, "InOut") => format!("*{name}"),
                _ => name.clone(),
            };
            if source == name {
                format!("        {name},\n")
            } else {
                format!("        {name}: {source},\n")
            }
        })
        .collect::<String>();
    let write_backs = event
        .parameters
        .iter()
        .filter(|parameter| parameter.direction == "InOut")
        .map(|parameter| {
            let name = to_snake(&parameter.name);
            let value = if parameter.kind == "Bool" {
                format!("i32::from(arguments.{name})")
            } else {
                format!("arguments.{name}")
            };
            format!("        *{name} = {value};\n")
        })
        .collect::<String>();

    format!(
        "pub const {iid_const}: Guid = {iid};\n\n\
         #[derive(Debug)]\n\
         pub struct {args_name} {{\n\
         {fields}}}\n\n\
         #[repr(C)]\n\
         struct {name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   invoke: unsafe extern \"system\" fn(*mut {name}{parameters}) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {name} {{ vtbl: *const {name}Vtbl }}\n\n\
         unsafe impl ComInterface for {name} {{ const IID: Guid = {iid_const}; }}\n\n\
         static {shouty}_VTBL: {name}Vtbl = {name}Vtbl {{\n\
         \x20   query_interface: {stem}_query_interface,\n\
         \x20   add_ref: {stem}_add_ref,\n\
         \x20   release: {stem}_release,\n\
         \x20   invoke: {stem}_invoke,\n\
         }};\n\n\
         pub fn {handler_fn}(callback: impl FnMut(&mut {args_name}) -> Result<()> + Send + 'static) -> ComPtr<{name}> {{\n\
         \x20   crate::event_callback::create({name} {{ vtbl: &{shouty}_VTBL }}, callback)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_query_interface(this: *mut IUnknown, iid: *const Guid, result: *mut *mut c_void) -> i32 {{\n\
         \x20   crate::event_callback::query_interface::<{name}, {args_name}>(this, iid, result)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_add_ref(this: *mut IUnknown) -> u32 {{\n\
         \x20   crate::event_callback::add_ref::<{name}, {args_name}>(this)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_release(this: *mut IUnknown) -> u32 {{\n\
         \x20   crate::event_callback::release::<{name}, {args_name}>(this)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_invoke(this: *mut {name}{parameters}) -> i32 {{\n\
         {null_checks}    let mut arguments = {args_name} {{\n\
         {initializers}    }};\n\
         \x20   let hr = crate::event_callback::invoke::<{name}, {args_name}>(this, &mut arguments);\n\
         \x20   if hr >= 0 {{\n\
         {write_backs}    }}\n\
         \x20   hr\n\
         }}\n",
        iid = guid_literal(&event.handler_interface_iid),
        handler_fn = event_handler_function(event),
    )
}

fn event_argument_type(parameter: &ProjectedParameter) -> &'static str {
    match parameter.kind.as_str() {
        "I32" => "i32",
        "I64" => "i64",
        "F32" => "f32",
        "F64" => "f64",
        "Bool" => "bool",
        "NullableBool" => "Option<bool>",
        "StringUtf16" if parameter.is_nullable => "Option<String>",
        "StringUtf16" => "String",
        _ => panic!("unsupported event argument kind {}", parameter.kind),
    }
}

fn emit_event(event: &ProjectedEvent) -> String {
    let snake = to_snake(&event.name);
    let handler = simple_name(&event.handler_interface_name);
    format!(
        "    pub fn advise_{snake}(&self, handler: &ComPtr<{handler}>) -> Result<i64> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut subscription_id = 0;\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().advise_{snake})(self.as_raw(), handler.as_raw(), &mut subscription_id);\n\
         \x20           hresult::check(hr).map(|_| subscription_id)\n\
         \x20       }}\n\
         \x20   }}\n\
         \x20   pub fn unadvise_{snake}(&self, subscription_id: i64) -> Result<()> {{\n\
         \x20       unsafe {{\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().unadvise_{snake})(self.as_raw(), subscription_id);\n\
         \x20           hresult::check(hr)\n\
         \x20       }}\n\
         \x20   }}\n"
    )
}

fn emit_factory(ir: &ProjectionIr) -> String {
    let mut types: Vec<_> = ir.types.iter().filter(|t| t.is_constructible).collect();
    types.sort_by(|left, right| left.full_name.cmp(&right.full_name));
    let iid = ir
        .factory_iid
        .as_deref()
        .expect("constructible projection requires factoryIid");
    let mut out = format!(
        "pub const IAVN_CONTROL_FACTORY_IID: Guid = {};\n\n",
        guid_literal(iid)
    );
    out.push_str("#[repr(C)]\nstruct IAvnControlFactoryVtbl {\n");
    emit_iunknown_slots(&mut out);
    for ty in &types {
        out.push_str(&format!(
            "    create_{}: unsafe extern \"system\" fn(*mut IAvnControlFactory, *mut *mut {}) -> i32,\n",
            to_snake(interface_suffix(&ty.name)),
            ty.name
        ));
    }
    for properties in attached_property_groups(ir) {
        let first = properties[0];
        let interface_name = simple_name(&first.statics_interface_name);
        out.push_str(&format!(
            "    get_{}_statics: unsafe extern \"system\" fn(*mut IAvnControlFactory, *mut *mut {}) -> i32,\n",
            to_snake(&first.owner_name),
            interface_name
        ));
    }
    if let Some(brush) = ir.brush_interface_name.as_deref() {
        let brush = simple_name(brush);
        let color = geometry::find("Color")
            .expect("Color geometry struct")
            .abi_name;
        out.push_str(&format!(
            "    create_solid_color_brush: unsafe extern \"system\" fn(*mut IAvnControlFactory, {color}, f64, *mut *mut {brush}) -> i32,\n"
        ));
    }
    out.push_str("}\n\n#[repr(C)]\npub struct IAvnControlFactory {\n    vtbl: *const IAvnControlFactoryVtbl,\n}\n\n");
    out.push_str("unsafe impl ComInterface for IAvnControlFactory {\n    const IID: Guid = IAVN_CONTROL_FACTORY_IID;\n}\n\n");
    out.push_str("impl ComPtr<IAvnControlFactory> {\n");
    for ty in types {
        let suffix = interface_suffix(&ty.name);
        out.push_str(&format!(
            "    pub fn create_{}(&self) -> Result<ComPtr<{}>> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut value = ptr::null_mut();\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_{})(self.as_raw(), &mut value);\n\
             \x20           hresult::check(hr)?;\n\
             \x20           ComPtr::from_projected_raw(value)\n\
             \x20       }}\n\
             \x20   }}\n",
            to_snake(suffix),
            ty.name,
            to_snake(suffix)
        ));
    }
    for properties in attached_property_groups(ir) {
        let first = properties[0];
        let owner = to_snake(&first.owner_name);
        let interface_name = simple_name(&first.statics_interface_name);
        out.push_str(&format!(
            "    pub fn get_{owner}_statics(&self) -> Result<ComPtr<{interface_name}>> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut value = ptr::null_mut();\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_{owner}_statics)(self.as_raw(), &mut value);\n\
             \x20           hresult::check(hr)?;\n\
             \x20           ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))\n\
             \x20       }}\n\
             \x20   }}\n"
        ));
    }
    if let Some(brush) = ir.brush_interface_name.as_deref() {
        let brush = simple_name(brush);
        let color = geometry::find("Color")
            .expect("Color geometry struct")
            .abi_name;
        out.push_str(&format!(
            "    pub fn create_solid_color_brush(&self, color: {color}, opacity: f64) -> Result<ComPtr<{brush}>> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut value = ptr::null_mut();\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_solid_color_brush)(self.as_raw(), color, opacity, &mut value);\n\
             \x20           hresult::check(hr)?;\n\
             \x20           ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))\n\
             \x20       }}\n\
             \x20   }}\n"
        ));
    }
    out.push_str("}\n");
    out
}

fn emit_attached_statics(properties: &[&ProjectedAttachedProperty]) -> String {
    let first = properties[0];
    let name = simple_name(&first.statics_interface_name);
    let iid_const = format!("{}_IID", to_shouty(name));
    let mut out = format!(
        "pub const {iid_const}: Guid = {};\n\n#[repr(C)]\nstruct {name}Vtbl {{\n",
        guid_literal(&first.statics_interface_iid)
    );
    emit_iunknown_slots(&mut out);
    for property in properties {
        let snake = to_snake(&property.name);
        let abi_type = rust_abi_type(&property.kind, None);
        out.push_str(&format!(
            "    get_{snake}: unsafe extern \"system\" fn(*mut {name}, *mut IAvnControl, *mut {abi_type}) -> i32,\n\
             \x20   set_{snake}: unsafe extern \"system\" fn(*mut {name}, *mut IAvnControl, {abi_type}) -> i32,\n"
        ));
    }
    out.push_str(&format!(
        "}}\n\n#[repr(C)]\npub struct {name} {{\n    vtbl: *const {name}Vtbl,\n}}\n\n\
         unsafe impl ComInterface for {name} {{\n    const IID: Guid = {iid_const};\n}}\n\n\
         impl ComPtr<{name}> {{\n"
    ));
    for property in properties {
        let snake = to_snake(&property.name);
        let abi_type = rust_abi_type(&property.kind, None);
        let result = match property.kind.as_str() {
            "Bool" => "value != 0",
            _ => "value",
        };
        let input = match property.kind.as_str() {
            "Bool" => "i32::from(value)".to_string(),
            "StringUtf16" => "value.as_ptr().cast_mut()".to_string(),
            _ => "value".to_string(),
        };
        // A string attached property reads back as the raw pointer the caller owns and writes
        // from a borrowed UTF-16 buffer, exactly like an ordinary string property; every other
        // kind is a scalar that crosses by value.
        let get_type = match property.kind.as_str() {
            "Bool" => "bool".to_string(),
            _ => rust_abi_type(&property.kind, None),
        };
        let set_type = match property.kind.as_str() {
            "Bool" => "bool".to_string(),
            "StringUtf16" => "&[u16]".to_string(),
            _ => rust_abi_type(&property.kind, None),
        };
        out.push_str(&format!(
            "    pub fn get_{snake}(&self, target: &ComPtr<IAvnControl>) -> Result<{get_type}> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut value: {abi_type} = {};\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_{snake})(self.as_raw(), target.as_raw(), &mut value);\n\
             \x20           hresult::check(hr).map(|_| {result})\n\
             \x20       }}\n\
             \x20   }}\n\
             \x20   pub fn set_{snake}(&self, target: &ComPtr<IAvnControl>, value: {set_type}) -> Result<()> {{\n\
             \x20       unsafe {{\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_{snake})(self.as_raw(), target.as_raw(), {input});\n\
             \x20           hresult::check(hr)\n\
             \x20       }}\n\
             \x20   }}\n",
            rust_abi_default(&property.kind)
        ));
    }
    out.push_str("}\n");
    out
}

fn attached_property_groups(ir: &ProjectionIr) -> Vec<Vec<&ProjectedAttachedProperty>> {
    let mut result: Vec<Vec<&ProjectedAttachedProperty>> = Vec::new();
    for property in &ir.attached_properties {
        if let Some(group) = result
            .iter_mut()
            .find(|group| group[0].statics_interface_name == property.statics_interface_name)
        {
            group.push(property);
        } else {
            result.push(vec![property]);
        }
    }
    result.sort_by(|left, right| {
        left[0]
            .statics_interface_name
            .cmp(&right[0].statics_interface_name)
    });
    result
}

fn emit_iunknown_slots(out: &mut String) {
    out.push_str(
        "    query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n",
    );
}

fn emit_property_slots(out: &mut String, ty: &ProjectedType, property: &ProjectedProperty) {
    if property.can_read {
        out.push_str(&format!(
            "    get_{}: unsafe extern \"system\" fn(*mut {}, *mut {}) -> i32,\n",
            to_snake(&property.name),
            ty.name,
            rust_abi_type(&property.kind, property.interface_name.as_deref())
        ));
    }
    if property.can_write {
        out.push_str(&format!(
            "    set_{}: unsafe extern \"system\" fn(*mut {}, {}) -> i32,\n",
            to_snake(&property.name),
            ty.name,
            rust_abi_type(&property.kind, property.interface_name.as_deref())
        ));
    }
}

fn emit_property(ty: &ProjectedType, property: &ProjectedProperty) -> String {
    let mut out = String::new();
    let snake = to_snake(&property.name);
    if property.can_read {
        let abi_type = rust_abi_type(&property.kind, property.interface_name.as_deref());
        out.push_str(&format!(
            "    pub fn get_{snake}(&self) -> Result<{}> {{\n        unsafe {{\n            let mut value: {abi_type} = {};\n            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_{snake})(self.as_raw(), &mut value);\n            hresult::check(hr)?;\n            {}\n        }}\n    }}\n",
            rust_property_type(property),
            rust_abi_default(&property.kind),
            rust_property_result(property)
        ));
    }
    if property.can_write {
        let (argument_type, argument_value) = rust_property_input(property);
        out.push_str(&format!(
            "    pub fn set_{snake}(&self, value: {argument_type}) -> Result<()> {{\n        unsafe {{\n            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_{snake})(self.as_raw(), {argument_value});\n            hresult::check(hr)\n        }}\n    }}\n"
        ));
    }
    let _ = ty;
    out
}

fn emit_method(_ty: &ProjectedType, method: &ProjectedMethod) -> String {
    let snake = to_snake(&method.name);
    let rust_args = method
        .parameters
        .iter()
        .filter(|p| p.direction != "Out")
        .map(|p| format!(", {}: {}", to_snake(&p.name), rust_parameter_input_type(p)))
        .collect::<String>();
    let out_params: Vec<_> = method
        .parameters
        .iter()
        .filter(|p| p.direction == "Out")
        .collect();
    let mut body = String::new();
    for parameter in &out_params {
        body.push_str(&format!(
            "            let mut {}: {} = {};\n",
            to_snake(&parameter.name),
            rust_abi_type(&parameter.kind, parameter.interface_name.as_deref()),
            rust_abi_default(&parameter.kind)
        ));
    }
    let call_args = method
        .parameters
        .iter()
        .map(rust_parameter_call_value)
        .collect::<Vec<_>>()
        .join(", ");
    let extra = if call_args.is_empty() {
        String::new()
    } else {
        format!(", {call_args}")
    };
    body.push_str(&format!(
        "            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().{snake})(self.as_raw(){extra});\n"
    ));
    let result = if out_params.is_empty() {
        "hresult::check(hr)".to_string()
    } else {
        let values = out_params
            .iter()
            .map(|p| to_snake(&p.name))
            .collect::<Vec<_>>();
        let value = if values.len() == 1 {
            values[0].clone()
        } else {
            format!("({})", values.join(", "))
        };
        format!("hresult::check(hr).map(|_| {value})")
    };
    format!(
        "    pub fn {snake}(&self{rust_args}) -> Result<{}> {{\n        unsafe {{\n{body}            {result}\n        }}\n    }}\n",
        rust_method_result_type(&out_params)
    )
}

fn vtbl_method_args(ty: &ProjectedType, method: &ProjectedMethod) -> String {
    let mut args = vec![format!("*mut {}", ty.name)];
    args.extend(method.parameters.iter().map(|p| {
        let abi = rust_abi_type(&p.kind, p.interface_name.as_deref());
        if p.direction == "Out" {
            format!("*mut {abi}")
        } else {
            abi
        }
    }));
    args.join(", ")
}

fn lineage<'a>(ir: &'a ProjectionIr, ty: &'a ProjectedType) -> Vec<&'a ProjectedType> {
    let mut result = vec![ty];
    let mut current = ty;
    while let Some(base) = &current.base_full_name {
        current = ir
            .types
            .iter()
            .find(|candidate| &candidate.full_name == base)
            .expect("base type must be present in projection IR");
        result.push(current);
    }

    result.reverse();
    result
}

fn unique_events(ir: &ProjectionIr) -> Vec<&ProjectedEvent> {
    let mut result = Vec::new();
    for event in ir.types.iter().flat_map(|ty| ty.events.iter()) {
        if !result.iter().any(|existing: &&ProjectedEvent| {
            existing.handler_interface_name == event.handler_interface_name
        }) {
            result.push(event);
        }
    }
    result
}

fn event_handler_function(event: &ProjectedEvent) -> String {
    let name = simple_name(&event.handler_interface_name)
        .strip_prefix("IAvn")
        .unwrap_or_else(|| simple_name(&event.handler_interface_name))
        .strip_suffix("Handler")
        .unwrap_or_else(|| {
            simple_name(&event.handler_interface_name)
                .strip_prefix("IAvn")
                .unwrap_or_else(|| simple_name(&event.handler_interface_name))
        });
    format!("{}_handler", to_snake(name))
}

fn rust_abi_type(kind: &str, interface_name: Option<&str>) -> String {
    if let Some(geometry) = geometry::find(kind) {
        return geometry.abi_name.into();
    }
    match kind {
        "I32" | "Bool" | "NullableBool" => "i32".into(),
        "I64" => "i64".into(),
        "F32" => "f32".into(),
        "F64" => "f64".into(),
        "StringUtf16" => "*mut u16".into(),
        "ComInterface" | "ComCollection" | "Brush" => {
            format!(
                "*mut {}",
                simple_name(interface_name.expect("interfaceName"))
            )
        }
        _ => "c_void".into(),
    }
}

fn rust_abi_default(kind: &str) -> &'static str {
    if geometry::is_geometry(kind) {
        return "Default::default()";
    }
    match kind {
        "F32" | "F64" => "0.0",
        "I32" | "I64" | "Bool" | "NullableBool" => "0",
        _ => "ptr::null_mut()",
    }
}

fn rust_property_type(property: &ProjectedProperty) -> String {
    if let Some(geometry) = geometry::find(&property.kind) {
        return geometry.abi_name.into();
    }
    match property.kind.as_str() {
        "I32" => "i32".into(),
        "I64" => "i64".into(),
        "F32" => "f32".into(),
        "F64" => "f64".into(),
        "Bool" => "bool".into(),
        "NullableBool" => "Option<bool>".into(),
        "StringUtf16" => "*mut u16".into(),
        "ComInterface" | "ComCollection" => {
            let ty = simple_name(property.interface_name.as_deref().expect("interfaceName"));
            if property.is_nullable {
                format!("Option<ComPtr<{ty}>>")
            } else {
                format!("ComPtr<{ty}>")
            }
        }
        // A brush is always optional: a control with no brush reports a null pointer.
        "Brush" => format!(
            "Option<ComPtr<{}>>",
            simple_name(property.interface_name.as_deref().expect("interfaceName"))
        ),
        _ => "()".into(),
    }
}

fn rust_property_result(property: &ProjectedProperty) -> String {
    match property.kind.as_str() {
        "Bool" => "Ok(value != 0)".into(),
        "NullableBool" => {
            "match value { -1 => Ok(None), 0 => Ok(Some(false)), 1 => Ok(Some(true)), _ => Err(Error(hresult::E_INVALIDARG)) }".into()
        }
        "ComInterface" if property.is_nullable => {
            "if value.is_null() { Ok(None) } else { Ok(Some(ComPtr::from_projected_raw(value)?)) }".into()
        }
        "ComCollection" if property.is_nullable => {
            "Ok(ComPtr::from_raw(value))".into()
        }
        "Brush" => "Ok(ComPtr::from_raw(value))".into(),
        "ComInterface" => {
            "ComPtr::from_projected_raw(value)".into()
        }
        "ComCollection" => {
            "ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))".into()
        }
        _ => "Ok(value)".into(),
    }
}

fn rust_property_input(property: &ProjectedProperty) -> (String, String) {
    match property.kind.as_str() {
        "Bool" => ("bool".into(), "i32::from(value)".into()),
        "NullableBool" => ("Option<bool>".into(), "value.map_or(-1, i32::from)".into()),
        "StringUtf16" if property.is_nullable => (
            "Option<&[u16]>".into(),
            "value.map_or(ptr::null_mut(), |v| v.as_ptr().cast_mut())".into(),
        ),
        "StringUtf16" => ("&[u16]".into(), "value.as_ptr().cast_mut()".into()),
        "ComInterface" | "ComCollection" if property.is_nullable => {
            let ty = simple_name(property.interface_name.as_deref().expect("interfaceName"));
            (
                format!("Option<&ComPtr<{ty}>>"),
                "value.map_or(ptr::null_mut(), ComPtr::as_raw)".into(),
            )
        }
        "Brush" => {
            let ty = simple_name(property.interface_name.as_deref().expect("interfaceName"));
            (
                format!("Option<&ComPtr<{ty}>>"),
                "value.map_or(ptr::null_mut(), ComPtr::as_raw)".into(),
            )
        }
        "ComInterface" | "ComCollection" => {
            let ty = simple_name(property.interface_name.as_deref().expect("interfaceName"));
            (format!("&ComPtr<{ty}>"), "value.as_raw()".into())
        }
        _ => (rust_property_type(property), "value".into()),
    }
}

fn rust_parameter_input_type(parameter: &ProjectedParameter) -> String {
    match parameter.kind.as_str() {
        "Bool" => "bool".into(),
        "NullableBool" => "Option<bool>".into(),
        "StringUtf16" if parameter.is_nullable => "Option<&[u16]>".into(),
        "StringUtf16" => "&[u16]".into(),
        "ComInterface" if parameter.is_nullable => format!(
            "Option<&ComPtr<{}>>",
            simple_name(parameter.interface_name.as_deref().expect("interfaceName"))
        ),
        "ComInterface" => format!(
            "&ComPtr<{}>",
            simple_name(parameter.interface_name.as_deref().expect("interfaceName"))
        ),
        _ => rust_abi_type(&parameter.kind, parameter.interface_name.as_deref()),
    }
}

fn rust_parameter_call_value(parameter: &ProjectedParameter) -> String {
    let name = to_snake(&parameter.name);
    if parameter.direction == "Out" {
        return format!("&mut {name}");
    }
    match parameter.kind.as_str() {
        "Bool" => format!("i32::from({name})"),
        "NullableBool" => format!("{name}.map_or(-1, i32::from)"),
        "StringUtf16" if parameter.is_nullable => {
            format!("{name}.map_or(ptr::null_mut(), |v| v.as_ptr().cast_mut())")
        }
        "StringUtf16" => format!("{name}.as_ptr().cast_mut()"),
        "ComInterface" if parameter.is_nullable => {
            format!("{name}.map_or(ptr::null_mut(), ComPtr::as_raw)")
        }
        "ComInterface" => format!("{name}.as_raw()"),
        _ => name,
    }
}

fn rust_method_result_type(parameters: &[&ProjectedParameter]) -> String {
    match parameters.len() {
        0 => "()".into(),
        1 => rust_abi_type(&parameters[0].kind, parameters[0].interface_name.as_deref()),
        _ => format!(
            "({})",
            parameters
                .iter()
                .map(|p| rust_abi_type(&p.kind, p.interface_name.as_deref()))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn guid_literal(iid: &str) -> String {
    let parts: Vec<&str> = iid.split('-').collect();
    if parts.len() != 5 {
        return "Guid::IUNKNOWN".into();
    }
    let d4 = parts[3].to_string() + parts[4];
    let bytes: Vec<String> = (0..8)
        .map(|i| format!("0x{}", &d4[i * 2..i * 2 + 2]))
        .collect();
    format!(
        "Guid {{ data1: 0x{}, data2: 0x{}, data3: 0x{}, data4: [{}] }}",
        parts[0],
        parts[1],
        parts[2],
        bytes.join(", ")
    )
}

fn interface_suffix(name: &str) -> &str {
    name.strip_prefix("IAvn").unwrap_or(name)
}

fn simple_name(full_name: &str) -> &str {
    full_name.rsplit('.').next().unwrap_or(full_name)
}

fn to_snake(name: &str) -> String {
    let mut out = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.extend(character.to_lowercase());
        } else {
            out.push(character);
        }
    }
    out
}

fn to_shouty(name: &str) -> String {
    to_snake(name).to_uppercase()
}
