use crate::ir::{ProjectedEvent, ProjectedProperty, ProjectedType, ProjectionIr};

pub fn emit_safe_module(ir: &ProjectionIr) -> String {
    let mut out = String::from(
        "//! Generated by avalonia-bindgen. Do not edit.\n\
         #![allow(dead_code)]\n\n\
         use avalonia_sys as sys;\n\
         use crate::{runtime::{with_factory, AsControl, EventSubscription}, Result};\n\n",
    );

    for projected_enum in &ir.enums {
        out.push_str("#[repr(i32)]\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
        out.push_str(&format!("pub enum {} {{\n", projected_enum.name));
        for value in &projected_enum.values {
            out.push_str(&format!("    {} = {},\n", value.name, value.value));
        }
        out.push_str("}\n\n");
        out.push_str(&format!(
            "impl TryFrom<i32> for {} {{\n\
             \x20   type Error = crate::Error;\n\
             \x20   fn try_from(value: i32) -> Result<Self> {{\n\
             \x20       match value {{\n",
            projected_enum.name
        ));
        for value in &projected_enum.values {
            out.push_str(&format!(
                "            {} => Ok(Self::{}),\n",
                value.value, value.name
            ));
        }
        out.push_str(
            "            _ => Err(crate::Error::InvalidEnumValue(value)),\n        }\n    }\n}\n\n",
        );
    }

    for collection in unique_collections(ir) {
        out.push_str(&emit_collection(collection));
        out.push('\n');
    }

    for ty in ir.types.iter().filter(|ty| ty.kind == "Class") {
        out.push_str(&emit_type(ir, ty));
        out.push('\n');
    }
    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

fn emit_collection(property: &ProjectedProperty) -> String {
    let name = simple_name(property.interface_name.as_deref().expect("interfaceName"));
    let safe_name = name.strip_prefix("IAvn").unwrap_or(name);
    let mut out = format!(
        "#[derive(Clone, Debug)]\n\
         pub struct {safe_name} {{\n\
         \x20   pub(crate) raw: sys::ComPtr<sys::{name}>,\n\
         }}\n\n"
    );
    out.push_str(&format!(
        "impl {safe_name} {{\n\
         \x20   pub fn len(&self) -> Result<usize> {{ Ok(self.raw.len()?) }}\n\
         \x20   pub fn is_empty(&self) -> Result<bool> {{ Ok(self.len()? == 0) }}\n"
    ));
    match property.element_kind.as_deref() {
        Some("ComInterface") => {
            let element = simple_name(
                property
                    .element_interface_name
                    .as_deref()
                    .expect("elementInterfaceName"),
            )
            .strip_prefix("IAvn")
            .unwrap();
            out.push_str(&format!(
                "    pub fn get(&self, index: usize) -> Result<{element}> {{\n\
                 \x20       Ok({element} {{ raw: self.raw.get(index)? }})\n\
                 \x20   }}\n\
                 \x20   pub fn add(&self, value: impl As{element}) -> Result<()> {{\n\
                 \x20       let value = value.as_{element_snake}()?;\n\
                 \x20       Ok(self.raw.add(&value)?)\n\
                 \x20   }}\n",
                element_snake = to_snake(element)
            ));
        }
        Some("StringUtf16") => out.push_str(
            "    pub fn get(&self, index: usize) -> Result<String> {\n\
             \x20       unsafe { sys::take_utf16(self.raw.get(index)?).ok_or(crate::Error::Abi(sys::Error(sys::E_POINTER))) }\n\
             \x20   }\n\
             \x20   pub fn add(&self, value: impl AsRef<str>) -> Result<()> {\n\
             \x20       let value: Vec<u16> = value.as_ref().encode_utf16().chain(Some(0)).collect();\n\
             \x20       Ok(self.raw.add(&value)?)\n\
             \x20   }\n\
             \x20   pub fn contains(&self, value: impl AsRef<str>) -> Result<bool> {\n\
             \x20       let value: Vec<u16> = value.as_ref().encode_utf16().chain(Some(0)).collect();\n\
             \x20       Ok(self.raw.index_of(&value)?.is_some())\n\
             \x20   }\n\
             \x20   pub fn remove_value(&self, value: impl AsRef<str>) -> Result<bool> {\n\
             \x20       let value: Vec<u16> = value.as_ref().encode_utf16().chain(Some(0)).collect();\n\
             \x20       if let Some(index) = self.raw.index_of(&value)? {\n\
             \x20           self.raw.remove(index)?;\n\
             \x20           Ok(true)\n\
             \x20       } else {\n\
             \x20           Ok(false)\n\
             \x20       }\n\
             \x20   }\n",
        ),
        kind => panic!("unsupported safe collection element kind {kind:?}"),
    }
    out.push_str(
        "    pub fn remove(&self, index: usize) -> Result<()> { Ok(self.raw.remove(index)?) }\n\
         \x20   pub fn clear(&self) -> Result<()> { Ok(self.raw.clear()?) }\n\
         }\n",
    );
    out
}

fn emit_type(ir: &ProjectionIr, ty: &ProjectedType) -> String {
    let safe_name = interface_suffix(&ty.name);
    let mut out = format!(
        "#[derive(Clone, Debug)]\n\
         pub struct {safe_name} {{\n\
         \x20   pub(crate) raw: sys::ComPtr<sys::{interface_name}>,\n\
         }}\n\n\
         impl {safe_name} {{\n",
        interface_name = ty.name
    );

    if ty.is_constructible {
        out.push_str(&format!(
            "    pub fn new() -> Result<Self> {{\n\
             \x20       with_factory(|factory| factory.create_{factory_name}())\n\
             \x20           .map(|raw| Self {{ raw }})\n\
             \x20   }}\n",
            factory_name = to_snake(safe_name)
        ));
    }

    for owner in lineage(ir, ty) {
        for property in &owner.properties {
            out.push_str(&emit_property(property));
            if property.kind == "ComCollection" && property.name == "Children" {
                out.push_str(
                    "    pub fn child(self, value: impl AsControl) -> Result<Self> {\n\
                     \x20       self.children()?.add(value)?;\n\
                     \x20       Ok(self)\n\
                     \x20   }\n",
                );
            }
            if property.kind == "ComCollection" && property.name == "Items" {
                out.push_str(
                    "    pub fn item(self, value: impl AsControl) -> Result<Self> {\n\
                      \x20       self.items()?.add(value)?;\n\
                      \x20       Ok(self)\n\
                      \x20   }\n",
                );
            }
        }
        for method in &owner.methods {
            out.push_str(&emit_method(method));
        }
        for event in &owner.events {
            out.push_str(&emit_event(event));
        }
    }
    for property in ir
        .attached_properties
        .iter()
        .filter(|property| property.owner_name == safe_name)
    {
        out.push_str(&emit_attached_property(property, ir));
    }
    out.push_str("}\n\n");

    if is_control(ir, ty) {
        out.push_str(&format!(
            "impl AsControl for {safe_name} {{\n\
             \x20   fn as_control(&self) -> Result<sys::ComPtr<sys::IAvnControl>> {{\n\
             \x20       Ok(self.raw.query_interface()?)\n\
             \x20   }}\n\
             }}\n"
        ));
    }

    fn emit_attached_property(
        property: &crate::ir::ProjectedAttachedProperty,
        ir: &ProjectionIr,
    ) -> String {
        let owner = to_snake(&property.owner_name);
        let name = to_snake(&property.name);
        let enum_name = simple_name(&property.managed_type_name);
        let is_enum = ir
            .enums
            .iter()
            .any(|projected_enum| projected_enum.full_name == property.managed_type_name);
        let safe_type = if is_enum {
            enum_name.to_string()
        } else {
            rust_scalar_kind(&property.kind).to_string()
        };
        let raw_get = if is_enum {
            format!("{enum_name}::try_from(value)")
        } else {
            "Ok(value)".to_string()
        };
        let raw_set = if is_enum { "value as i32" } else { "value" };
        format!(
            "    pub fn get_{name}(target: &impl AsControl) -> Result<{safe_type}> {{\n\
             \x20       let target = target.as_control()?;\n\
             \x20       let value = with_factory(|factory| factory.get_{owner}_statics()?.get_{name}(&target))?;\n\
             \x20       {raw_get}\n\
             \x20   }}\n\
             \x20   pub fn set_{name}(target: &impl AsControl, value: {safe_type}) -> Result<()> {{\n\
             \x20       let target = target.as_control()?;\n\
             \x20       with_factory(|factory| factory.get_{owner}_statics()?.set_{name}(&target, {raw_set}))\n\
             \x20   }}\n"
        )
    }
    out
}

fn emit_property(property: &ProjectedProperty) -> String {
    let snake = to_snake(&property.name);
    let getter = if property.can_write {
        format!("get_{snake}")
    } else {
        snake.clone()
    };
    let builder = if property.kind == "Bool" || property.kind == "NullableBool" {
        snake.strip_prefix("is_").unwrap_or(&snake)
    } else {
        &snake
    };
    let mut out = String::new();

    if property.can_read {
        match property.kind.as_str() {
            "StringUtf16" if property.is_nullable => out.push_str(&format!(
                "    pub fn {getter}(&self) -> Result<Option<String>> {{\n\
                 \x20       unsafe {{ Ok(sys::take_utf16(self.raw.get_{snake}()?)) }}\n\
                 \x20   }}\n"
            )),
            "StringUtf16" => out.push_str(&format!(
                "    pub fn {getter}(&self) -> Result<String> {{\n\
                 \x20       unsafe {{ sys::take_utf16(self.raw.get_{snake}()?).ok_or(crate::Error::Abi(sys::Error(sys::E_POINTER))) }}\n\
                 \x20   }}\n"
            )),
            "ComInterface" => {
                let safe_type = interface_suffix(simple_name(
                    property.interface_name.as_deref().expect("interfaceName"),
                ));
                if property.is_nullable {
                    out.push_str(&format!(
                        "    pub fn {getter}(&self) -> Result<Option<{safe_type}>> {{\n\
                         \x20       Ok(self.raw.get_{snake}()?.map(|raw| {safe_type} {{ raw }}))\n\
                         \x20   }}\n"
                    ));
                } else {
                    out.push_str(&format!(
                        "    pub fn {getter}(&self) -> Result<{safe_type}> {{\n\
                         \x20       Ok({safe_type} {{ raw: self.raw.get_{snake}()? }})\n\
                         \x20   }}\n"
                    ));
                }
            }
            "ComCollection" => {
                let safe_type = interface_suffix(simple_name(
                    property.interface_name.as_deref().expect("interfaceName"),
                ));
                out.push_str(&format!(
                    "    pub fn {getter}(&self) -> Result<{safe_type}> {{\n\
                     \x20       Ok({safe_type} {{ raw: self.raw.get_{snake}()? }})\n\
                     \x20   }}\n"
                ));
            }
            "I32" if is_enum_property(property) => {
                let enum_name = simple_name(property.managed_type_name.as_deref().unwrap());
                out.push_str(&format!(
                    "    pub fn {getter}(&self) -> Result<{enum_name}> {{\n\
                     \x20       let value = self.raw.get_{snake}()?;\n\
                     \x20       {enum_name}::try_from(value)\n\
                     \x20   }}\n"
                ));
            }
            _ => out.push_str(&format!(
                "    pub fn {getter}(&self) -> Result<{}> {{ Ok(self.raw.get_{snake}()?) }}\n",
                safe_scalar_type(property)
            )),
        }
    }

    if property.can_write {
        let (argument, setup, value) = safe_property_input(property);
        out.push_str(&format!(
            "    pub fn set_{builder}(&self, value: {argument}) -> Result<()> {{\n{setup}        Ok(self.raw.set_{snake}({value})?)\n    }}\n\
             \x20   pub fn {builder}(self, value: {argument}) -> Result<Self> {{\n\
             \x20       self.set_{builder}(value)?;\n\
             \x20       Ok(self)\n\
             \x20   }}\n"
        ));
    }
    out
}

fn emit_event(event: &ProjectedEvent) -> String {
    assert_eq!(event.payload_kind, "None", "unsupported event payload kind");
    let event_name = to_snake(&event.name);
    let handler_name = simple_name(&event.handler_interface_name)
        .strip_prefix("IAvn")
        .unwrap_or_else(|| simple_name(&event.handler_interface_name))
        .strip_suffix("Handler")
        .unwrap_or_else(|| {
            simple_name(&event.handler_interface_name)
                .strip_prefix("IAvn")
                .unwrap_or_else(|| simple_name(&event.handler_interface_name))
        });
    let handler_function = format!("{}_handler", to_snake(handler_name));
    format!(
        "    pub fn subscribe_{event_name}(&self, mut callback: impl FnMut(()) + Send + 'static) -> Result<EventSubscription> {{\n\
         \x20       let handler = sys::{handler_function}(move || {{\n\
         \x20           callback(());\n\
         \x20           Ok(())\n\
         \x20       }});\n\
         \x20       let subscription_id = self.raw.advise_{event_name}(&handler)?;\n\
         \x20       let source = self.raw.clone();\n\
         \x20       Ok(EventSubscription::new(move || source.unadvise_{event_name}(subscription_id)))\n\
         \x20   }}\n\
         \x20   pub fn on_{event_name}(self, callback: impl FnMut(()) + Send + 'static) -> Result<Self> {{\n\
         \x20       self.subscribe_{event_name}(callback)?.detach();\n\
         \x20       Ok(self)\n\
         \x20   }}\n"
    )
}

fn emit_method(method: &crate::ir::ProjectedMethod) -> String {
    let name = to_snake(&method.name);
    let arguments = method
        .parameters
        .iter()
        .map(|parameter| {
            let parameter_name = to_snake(&parameter.name);
            if parameter.kind == "ComInterface" {
                let safe = interface_suffix(simple_name(
                    parameter.interface_name.as_deref().expect("interfaceName"),
                ));
                format!("{parameter_name}: &{safe}")
            } else {
                format!("{parameter_name}: {}", rust_scalar_kind(&parameter.kind))
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let call_arguments = method
        .parameters
        .iter()
        .map(|parameter| {
            let parameter_name = to_snake(&parameter.name);
            if parameter.kind == "ComInterface" {
                format!("&{parameter_name}.raw")
            } else {
                parameter_name
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let separator = if arguments.is_empty() { "" } else { ", " };
    format!(
        "    pub fn {name}(&self{separator}{arguments}) -> Result<()> {{ Ok(self.raw.{name}({call_arguments})?) }}\n"
    )
}

fn safe_property_input(property: &ProjectedProperty) -> (String, String, String) {
    match property.kind.as_str() {
        "StringUtf16" => (
            "impl AsRef<str>".into(),
            "        let value: Vec<u16> = value.as_ref().encode_utf16().chain(Some(0)).collect();\n"
                .into(),
            if property.is_nullable {
                "Some(&value)".into()
            } else {
                "&value".into()
            },
        ),
        "ComInterface" => (
            "impl AsControl".into(),
            "        let value = value.as_control()?;\n".into(),
            if property.is_nullable {
                "Some(&value)".into()
            } else {
                "&value".into()
            },
        ),
        "I32" if is_enum_property(property) => (
            simple_name(property.managed_type_name.as_deref().unwrap()).into(),
            String::new(),
            "value as i32".into(),
        ),
        _ => (
            safe_scalar_type(property),
            String::new(),
            "value".into(),
        ),
    }
}

fn safe_scalar_type(property: &ProjectedProperty) -> String {
    if property.kind == "I32" && is_enum_property(property) {
        simple_name(property.managed_type_name.as_deref().unwrap()).into()
    } else {
        rust_scalar_kind(&property.kind).into()
    }
}

fn rust_scalar_kind(kind: &str) -> &str {
    match kind {
        "I32" => "i32",
        "I64" => "i64",
        "F32" => "f32",
        "F64" => "f64",
        "Bool" => "bool",
        "NullableBool" => "Option<bool>",
        _ => "()",
    }
}

fn is_enum_property(property: &ProjectedProperty) -> bool {
    property.kind == "I32" && property.managed_type_name.as_deref() != Some("System.Int32")
}

fn is_control(ir: &ProjectionIr, ty: &ProjectedType) -> bool {
    lineage(ir, ty)
        .iter()
        .any(|candidate| candidate.name == "IAvnControl")
}

fn lineage<'a>(ir: &'a ProjectionIr, ty: &'a ProjectedType) -> Vec<&'a ProjectedType> {
    let mut result = vec![ty];
    let mut current = ty;
    while let Some(base) = &current.base_full_name {
        current = ir
            .types
            .iter()
            .find(|candidate| &candidate.full_name == base)
            .expect("base type must be present in projection IR");
        result.push(current);
    }
    result.reverse();
    result
}

fn unique_collections(ir: &ProjectionIr) -> Vec<&ProjectedProperty> {
    let mut result = Vec::new();
    for property in ir
        .types
        .iter()
        .flat_map(|ty| ty.properties.iter())
        .filter(|property| property.kind == "ComCollection")
    {
        if !result
            .iter()
            .any(|existing: &&ProjectedProperty| existing.interface_name == property.interface_name)
        {
            result.push(property);
        }
    }
    result
}

fn interface_suffix(name: &str) -> &str {
    name.strip_prefix("IAvn").unwrap_or(name)
}

fn simple_name(full_name: &str) -> &str {
    full_name.rsplit('.').next().unwrap_or(full_name)
}

fn to_snake(name: &str) -> String {
    let mut out = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.extend(character.to_lowercase());
        } else {
            out.push(character);
        }
    }
    out
}
